var v = "题库题数：1546（2015.05.09更新）";
alert("脚本加载完成。\n如果您为使用此脚本支付了任何费用，那么恭喜您，您被坑了。\n\n按确定开始执行。");
var b = function(q){
  switch(q){
// 211 | 7 + 54 | 7 + 266 | 0 + 26 | 0 + 4 | 0 + 20 | 1 + 19 | 1 + 597 | 0 + 23 | 0 + 18 > 1254
// 0 + 14 | 0 + 9 | 0 + 44 | 0 + 225 > 292
// 1254 + 292 > 1546
//题库01（已确认） - 211道 - 【群主】？（1043201997）提供 - 2014.05.04
case "Bilibili采用邀请码注册，注册满几个月以上的用户才能购买邀请码？": return "三个月";
case "自古红蓝出什么？": return "CP";
case "官方逼死了谁？": return "同人";
case "下面哪位是个中二少女": return "小鸟游六花";
case "暴漫中“荆轲刺秦王”的下一句是": return "两条毛腿肩上扛";
case "团战可以输，____必须死？": return "提莫";
case "《命运石之门》中凤凰院凶真的配音是？": return "宫野真守";
case "以下哪部动漫不是京阿尼（京都动画公司）制作的？": return "FZ";
case "《海贼王》的作者是谁？": return "尾田荣一郎";
/*10*/case "《科学的超电磁炮》中，Lever.5被称为？": return "超能力者";
case "《魔法少女小圆》的导演是谁？": return "新房昭之";
case "奥特曼来自哪个星云？": return "m78";
case "奥特曼的家在哪里": return "M78";
case "《龙与虎》中的龙指的是谁？": return "高须龙儿";
case "十万个冷笑话是哪家漫画网连载的": return "有妖气";
case "地球距离月球之间的距离为？": return "384,400千米";
case "网络上11区指的是那个国家？": return "日本";
case "日语“我爱你”的空耳是什么？": return "阿姨洗铁路";
case "《某科学的超电磁炮》中，佐天同学经常对初春同学做的一件事情是什么？": return "掀裙";
/*20*/case "著名虚拟偶像初音未来的声源是谁？": return "藤田咲";
case "沙盒游戏“我的世界”的英文名是什么？": return "minecraft";
case "《Fate/ZERO》中Saber的Master是谁？": return "卫宫切嗣";
case "《魔法的禁书目录》中的特殊能力是什么？": return "魔法和超能力";
case "自称为“爱的战士”的人是谁？": return "虚渊玄";
case "请问FFF团的宗旨是什么？": return "烧死异性恋";
case "电磁炮四主角中谁的能力是空间移动？": return "白井黑子";
case "宅界的“东方”指的是什么": return "东方project";
case "桂木桂马自封的称号是？": return "攻略之神";
case "《魔法少女小圆》中巴麻美学姐是哪一话死的？": return "第三话";
/*30*/case "《 某科学的超电磁炮》中 最后之作 的检体番号是多少？": return "检体番号20001";
case "哪个不属于“钉宫四萌”？": return "神乐";
case "以下动漫少女哪个是金色双马尾？": return "A三千院凪";
case "三国杀online中，马超的台词是？": return "全军突击";
case "《千本樱》的原唱是谁？": return "初音未来";
case "《这样算是僵尸吗？》中优克莉伍德·海尔赛兹的能力是？": return "言灵";
case "“我已经看到结局了”这句经典台词是出自于哪部动画？": return "《只有神知道的世界》";
case "钉宫理惠的无路赛一般为多少个": return "3";
case "TO LOVE中大家喜闻乐见的小姨子是谁": return "梦梦";
case "《天降之物》里，伊卡洛斯最喜欢什么水果？": return "西瓜";
/*40*/case "《龙与虎》中逢坂大河和谁终成眷属": return "高须龙儿";
case "计算机编程中常见的if语句是？": return "判断语句";
case "《某科学的超电磁炮S》中的御坂美琴用什么放电磁炮？": return "用硬币";
case "被动漫爱好者称之为“梨神”的所属动漫作品是下列哪一项？": return "《To Loveる》";
case "动漫，漫画，游戏的简称是什么": return "ACG";
case "历代《口袋妖怪》的三只初始口袋妖怪的属性是？": return "草、水、火";
case "动漫《缘之空》的女主角叫什么名字？": return "春日野穹";
case "水的化学式怎么书写？": return "H₂O";
case "下列哪个动漫角色不是竹达彩奈配音的妹系角色？": return "住之江亚香-亲吻姐姐";
case "下列那种描述最接近“MAD”的含义？": return "二次创作影像";
/*50*/case "一种类似人生掌控者的，也指脱宅后大部分时间花在现实生活中的人": return "现充";
case "以下哪部作品不是京都制作的？": return "little busters";
case "陆逊一手牌无中，当他使用完之后（未被无懈）会得到几张手牌？": return "三张";
case "第一宇宙速度是？km/s": return "7.9";
case "凉宫春日是什么团的团长？": return "SOS团";
case "肥料掺了____，一袋能顶两袋撒": return "金坷垃";
case "哪个角色被叫做bilibili？": return "御坂美琴";
case "天才麻将少女中宫永咲擅长以什么方式胡牌": return "岭上开花";
case "宫永咲的绰号是什么？": return "大魔王";
case "《潜行吧！奈亚子》中克子的本体是什么？": return "克图格亚星人";
/*60*/case "《某科学的超电磁炮》的女主角御坂美琴在动漫界的俗称为": return "炮姐";
case "德布罗意波长公式是？": return "E=hv";
case "\"世界已完蛋\"出自哪部作品": return "奈亚子";
case "直到我膝盖中了一箭出自哪里": return "上古卷轴5";
case "《狼与香辛料》的作者是谁？": return "支仓冻砂";
case "《天才麻将少女》的女主角宫永咲在什么情况下麻将实力较强？": return "不穿袜子时";
case "KEY社三大“催泪弹”不包括": return "FATE/STAY NIGHT";
case "《命运石之门》中的椎名 真由理的配音是谁": return "花泽香菜";
case "fate stay night和fate zero中的吉尔伽美什别称什么？": return "金闪闪";
case "《某科学的超电磁炮》中“炮姐”是指以下哪人？": return "御坂美琴";
/*70*/case "被网友称为“世界第一吃货殿下”的是": return "洛天依";
case "枪兵的幸运等级": return "E";
case "以下哪个不是高级程序设计语言": return "汇编语言";
case "扶他出去!": return "YOOOOOO";
case "下列哪个不是Microsoft产品": return "Android";
case "X在叫，人坏掉，请问X是什么": return "蝉";
case "《天降小册子》L 不抱膝坐，推理能力会降低多少？": return "40%";
case "“我的XX可是突破天际的XX”中XX指的是什么": return "钻头";
case "请问洛天依的声源是谁？": return "山新";
case "未来日记中我妻由乃的声优是谁": return "村田知沙";
/*80*/case "最强的肥料是什么？": return "金坷垃";
case "下列人物中头上没有呆毛的是？": return "冈崎汐";
case "SAO是下列哪部动漫的缩写？": return "刀剑神域";
case "邪王真眼的拥有者": return "小鸟游六花";
case "老滚是哪个著名RPG游戏的昵称？（中文四字）": return "上古卷轴";
case "常言道，FFF團不燒什麼？": return "真愛";
case "B站会员初始收藏视频上限是多少？": return "40";
case "声优钉宫理惠配音的角色常常没有？": return "胸";
case "【夜神月】千本櫻 ——你认为此视频最有可能出现在哪里？": return "二次元鬼畜";
case "三国杀online中，董卓的台词是？": return "我是不是该减肥啦";
/*90*/case "和我签订契约，成为____吧": return "魔法少女";
case "以下不是niconico御三家的是": return "魔法少女小圆";
case "《日常》中名乃的真实身份是？": return "机器人";
case "马猴烧酒是什么东东？": return "魔法少女";
case "动漫中转学生一般不可能是？": return "普通学生";
case "对于新番动画，每年第一季度是？（2字）": return "冬季";
case "“給我一個支點，我可以撬動地球。”这句话是谁说的？": return "阿基米德";
case "轻音少女平泽唯的声优是？": return "丰崎爱生";
case "殴打小朋友系列的作者是谁？": return "狗HANK";
case "以下哪位动漫角色没有呆毛": return "不破爱花（绝园的暴风雨）";
/*100*/case "东方Project中简称为红白的是谁？": return "博丽灵梦";
case "吉田松阳的声优是": return "山寺宏一";
case "平乳是稀缺___": return "资源";
case "游戏《上古卷轴》里最经常中箭的地方是？": return "膝盖";
case "炮姐的真名叫做？": return "御坂美琴";
case "请问PSP上以下哪个键不不存在的？": return "C";
case "“打麻将真开心啊”出自下列哪部动漫？": return "咲-SAKI";
case "以下哪个不属于钉宫四萌？": return "神崎·H·亚里亚";
case "Vividred Operation的官方twitter名叫什么？": return "ビビッドレッド・オペレーション";
case "ACG界名词“京阿尼”指的是？": return "京都动画公司";
/*110*/case "下列哪国人没有参加金坷垃的争夺？": return "韩国人";
case "言叶之庭的导演是谁？": return "新海诚";
case "三国杀可以使用下列哪个技能自杀？": return "驱虎";
case "wow中被称为小芊芊的职业是": return "盗贼";
case "FFF团的出处是哪里呢？": return "笨蛋，测验，召唤兽";
case "一切都是谁的错？": return "时臣";
case "“荆轲刺秦王，两条毛腿肩上扛。”出自哪里？": return "暴走漫画";
case "“不学礼，无以立”。出于何处？": return "《论语》";
case "自古红蓝出什么": return "CP";
case "声优御三家不包括？": return "植田佳奈";
/*120*/case "TV动画《狼与香辛料》当中，男主角罗伦斯的配音是谁？": return "福山润";
case "刀剑神域的男主角是谁？": return "桐谷和人";
case "白井黑子什麼時候出生？": return "7月14日";
case "凉宫春日又称": return "团长";
case "“真相只有一个！”这句经典台词出自于哪部动画？ ": return "《名侦探柯南》";
case "三爷有几块腹肌？": return "8块";
case "《天降之物》中笨蛋是谁？": return "阿斯特蕾亚";
case "《FATE》中saber不愿意被士狼看到自己洗澡的原因是": return "纯害羞";
case "椎名真白的声优是？": return "茅野爱衣";
case "少男少女患有一种妄想拯救世界或毁灭世界的疾病，这种病叫做？": return "中二病";
/*130*/case "泽城美雪在《蔷薇少女》中为哪个角色配音？": return "真红";
case "DOTA地图的作者是谁？": return "冰蛙";
case "bilibili的吉祥物是那两个？": return "22娘和33娘";
case "红白指的是东方幻想乡的哪个人物？": return "新垣结衣";
case "________虚渊玄？": return "爱的战士";
case "《海贼王》中娜美的声优是谁？": return "冈村明美";
case "小仓唯高三上学期期末考试几门90分以上？": return "8门";
case "lol中武器大师的武器是什么？": return "路灯";
case "金，木，水，火，___": return "土";
case "东方二小姐的名字叫什么": return "芙兰朵露·斯卡雷特";
/*140*/case "SAO中“桐人”在现实世界的真名叫什么？": return "桐谷和人";
case "下面哪样东西才是男人的浪漫?": return "钻头";
case "三千院 凪 字怎么念": return "zhi";
case "《轻音少女》中平泽唯对自己的吉他起名为?": return "吉太";
case "东方绯想天是什么类型的游戏": return "弹幕格斗";
case "《AngelBeats！》中“天使”的真名是？": return "立华奏";
case "《夏目友人帐》中的白猪是什么动物？": return "猫";
case "《迷茫管家与懦弱的我》中的坂町近次郎患有什么恐惧症？": return "女生恐惧症";
case "动画《美食的俘虏》中，拥有”发网“技能的是": return "萨尼";
case "棋魂中小光职业考试一共输了几场？": return "3场";
/*150*/case "元首最常去的是哪个省？": return "河北省";
case "宝具“招荡的黄金剧场”出自FATE系列的那部？": return "Fate/extra";
case "动画《code geass 叛逆的鲁路修》的监督是谁？": return "谷口悟朗";
case "中二病也要谈恋爱女主": return "小鸟游六花";
case "《少女绮想曲》又名：……？": return "少女祈祷曲";
case "“你已经死了”是谁的名句？": return "健次郎";
case "clannad游戏发行公司是？": return "KEY社";
case "《CLANNAD》的制作公司是什么？": return "Key社";
case "爱酱大胜利出自哪部动画": return "夹在我女友和青梅竹马间的各种修罗场";
case "以下哪个不是key社的游戏？": return "angel beats";
/*160*/case "《刀剑神域》tv版是改编自______?": return "轻小说";
case "剧情高潮时突然切片尾曲，这时应该说什么？": return "这是人干的事么？";
case "出自动画《天才麻将少女》的名言“打麻将真TM开心啊”是谁说的？": return "宫永咲";
case "被称做团长的是哪位动漫人物？": return "凉宫春日";
case "初音ミケ的生日是？": return "2007 08 31";
case "《樱花庄的宠物女孩》中之中茅野爱衣的配音是谁": return "椎名真白";
case "几颗星的龙珠是孙悟空的爷爷所持有的？": return "四星球";
case "银魂中坂田银时的刀是以哪种方式购得？": return "电视购物";
case "“妹中剑”源自以下哪部作品？": return "罪恶王冠";
case "动画CLANNAD中伊吹风子的配音是谁？": return "野中蓝";
/*170*/case "WOT中以下哪台战车不属于S系": return "T-40";
case "保时捷911车系采用的引擎种类是": return "水平对置6缸";
case "《死神》作者是谁？": return "久保带人";
case "动画《南家三姐妹》，下列选项中，那个角色不属于三姐妹？": return "南冬马";
case "《凉宫春日的分裂》与《凉宫春日的惊愕》的发售日期相隔多少天？": return "1515";
case "在Minecraft原版中，可以在炉子中烤熟食用的是": return "土豆";
case "初版帝国时代2，可选国家不包括以下哪一个": return "埃及";
case "正统妹控游戏缘之空后作叫什么名字？": return "悠之空";
case "爆漫王里，男主角的女朋友是干什么的？": return "声优";
case "动漫《狼与香辛料》中，男主角罗伦斯从事的什么职业？": return "旅行商人";
/*180*/case "英雄联盟的英文缩写是？": return "LOL";
case "东方中⑨的原名是什么": return "琪露诺";
case "十六夜咲夜初登場時的主題曲是什麽？": return "月時計　～ ルナ・ダイアル";
case "《魔笛magi》的OP1是？": return "V.I.P";
case "《空之境界》中，两仪式拥有能力的眼睛叫什么名字": return "A.直死之魔眼";
case "什么是“DTS”": return "数字家庭影院系统";
case "动画《裁断分离之罪恶剪刀》中，男主角会对什么产生兴奋": return "长发";
case "《命运石之门》中最终达到的SG世界线的世界线变动率是多少？": return "1.048596%";
case "澄空学园出自哪一部游戏作品？": return "秋之回忆";
case "《超级马里奥兄弟》中马里奥可以通过吃什么来长大？": return "蘑菇";
/*190*/case "《JOJO奇妙冒险》中空条承太郎的替身使者的名字叫什么？": return "白金之星";
case "“不能通过有限步骤将物体降温到0K”是__的表述": return "热力学第三定律";
case "Hao说“不拿冠军砍手”时是在哪个战队？": return "XFY";
case "一个合格的FFF团团员当看到男女主角过于亲密时,应": return "烧";
case "物语系列中小忍的名字是谁起的？": return "忍野咩咩";
case "Jojo的奇妙冒险中，第二代jojo的配音还参与过哪部动漫的配音？": return "银魂";
case "以下哪个角色不是钉宫四萌之一？": return "阿尔冯斯·艾尔利克";
case " 薛定谔因某个著名假说而获得了一下哪个外号？": return "虐猫狂人";
case "bilibili7个板块中不存在的是？": return "新闻";
case "ACG界魔都指什么地方": return "上海";
/*200*/case "《CLANNAD》中，藤林杏的摩托车是什么颜色的？": return "白色";
case "以下哪个人物出自东方project？": return "西行寺幽幽子";
case "VOCALOID3发布后，新增的歌手是": return "洛天依";
case "“龙破斩”是《魔剑美神》中哪的角色的得意技？": return "莉娜·因巴斯";
case "白娅·杜·罗德·赫尔梅尼姆的声优是谁？": return "早见沙织";
case "ef中新藤千寻的记忆停留在了多少岁？": return "12";
case "每年的11月11日是什么节日(3个字": return "光棍节";
case "《中二病也要恋爱！》中小鸟游六花的姐姐是谁？": return "小鸟游十花";
case "汞的元素符号是？": return "Hg";
case "《丹特丽安的书架》是哪个公司制作的": return "GAINAX";
/*210*/case "日本哪个地方因亚洲表情新巨头而出名？": return "兵库北";
case "LOL的历史背景中光辉女郎属于哪个阵营？": return "德玛西亚";
//题库02（已确认） - 7道 - 优子（352275201）提供 - 2014.05.05
case "动漫《刀剑神域》中亚丝娜的角色歌歌名为？": return "My Independent Destiny";
case "当PCl5 = PCl3 +Cl2的化学平衡常数Kc=1.8M时，在0.5L的容器中加入0.15molPCl5,求平衡后Cl2的浓度": return "0.26M";
case "《怪物猎人3G》中两只奇面族的名字分别叫什么？": return "茶茶，卡扬巴";
case "以下角色与其他角色性别不同的是？": return "木下秀吉";
case "《玉子超市》中牧野神奈的配音是谁？": return "长妻树里";
case "160兵长的声优是？": return "娘娘";
case "无头骑士的声优是谁？": return "泽城美雪";
//题库02（未确认） - 54道 - 优子（352275201）提供 - 2014.05.05
case "「蓝蓝路教主」中「教主」的形象原型出自哪一个连锁饮食业公司？": return "麦当劳";
case "《叛逆的鲁鲁修》中的鲁鲁修的配音是谁?": return "福山润";
case "名曲《最珍贵的宝物》（“一番の宝物”）出自哪个作品？": return "Angel Beats";
case "洛天依中文音源是由哪位声优提供？": return "山新";
case "FSN和FZ中吉尔伽美什的真正宝具是什么": return "王之财宝";
case "《圣斗士》中黄金圣衣一共有多少件？": return "12件";
case "游戏《星际争霸》《暗黑破坏神》等是哪个公司制作的？": return "Blizzard";
case "代号47是哪个游戏中的主角？": return "杀手";
case "APH中意呆的声优是谁": return "浪川大辅";
case "C语言中，如果ar是个数组，那么表达式ar[i]与什么等价？": return "*(ar+i)";
case "銀魂中\"昙天\"是什麼意思?": return "阴天";
case "《扑杀天使》中小骷髅的咒语是什么？": return "哔哔噜哔噜哔噜哔哔噜哔";
case "阿良良木历帮谁刷牙了？": return "火怜";
case "化物语的监督是谁？": return "新房昭之";
case "零之使魔中露易丝在托里斯汀所打工的酒馆前身叫什么": return "鳗鱼之睡床";
case "以下声优中被称为组长的是": return "杉田智和";
case "成年人及年长儿正常心胸比例不大于": return "0.5";
case "海贼王的作者是？": return "尾田荣一郎";
case "我国大陆家庭电路的电压统一使用为多少伏？": return "220";
case "著名武打男星比利海灵顿最常从事的体育运动是？": return "摔跤";
case "北极熊的毛是什么颜色？": return "透明";
case "美树沙耶加所爱的人是谁？": return "上条恭介";
case "《潜行吧！奈亚子》中邪神奈亚拉托提普的天敌是？": return "克图格亚";
case "下列人物不属于黑白后宫的是": return "博丽灵梦";
case "罪恶王冠男主的名字": return "樱满集";
case "浦科特m5p固态硬盘采用的是什么主控芯片": return "Marvell 88SS9187-BLD2";
case "著名游戏制作人板垣伴信的绰号是什么？": return "硫酸脸";
case "《AIR》的女主角的名字？": return "神尾观铃";
case "凉宫的小说中无尽的八月一共重复了多少遍？": return "15532";
case "《Fate/zero》的剧本是谁写的？": return "虚渊玄";
case "被称为神谷娘娘的是哪位声优？": return "神谷浩史";
case "未来日记中我妻由乃的声优是谁": return "村田知沙";
case "新生物性状产生的根本原因在于？": return "基因重组";
case "绫崎飒一开始欠下的债务是": return "¥150000000";
case "《神薙》中花泽香菜的角色是？": return "忏悔酱 ";
case "12年底被广泛玩坏的转手指op是出自哪部动画。": return "中二病也要谈恋爱";
case "以下哪部作品的监督不是新房昭之？": return "夏目友人帐";
case "动漫《火影忍者》中，宇智波佐助所拥有的瞳术的名字是？": return "写轮眼";
case "下列哪种角色不属于暴雪游戏《暗黑破坏神3》？": return "程序员";
case "以下KEY社的游戏的剧本创作，哪个麻枝准没有参与？": return "REWRITE";
case "罪恶王冠的拔剑神曲是谁写的": return "泽野弘之";
case "《寒蝉鸣泣之时》中的古手梨花的口头禅是什么？": return "咪啪 ";
case "以下轩辕剑的哪一部作品主角是女性？": return "苍之涛";
case "金坷垃好处都有啥（下一句话": return "谁说对了就给他";
case "NICONICO表·御三家不包括": return "创价学会";
case "物质波是由谁提出来的": return "德布罗意";
case "《天空之城》的主题曲是什么？": return "伴随着你";
case "请问下列哪首V家歌曲以“就不给人翻唱”而闻名？": return "初音ミクの消失";
case "以下电视台总部位于香港的是？": return "凤凰卫视";
case "烧死异性恋的FFF团源自哪部日本动漫。": return "笨蛋测验召唤师";
case "《魔法禁书目录》中的上条当麻是如何让特异能力无效化的？": return "使用右手";
case "阿拉垃圾君是谁的外号": return "阿良良木历";
case "比利是教什么科目的": return "哲学";
case "只有神知道的世界中的偶像通常指的是谁？": return "中川花音";
//题库03（已确认） - 7道 - 优子（352275201）提供 - 2014.04.30
case "TV动画《进撃の巨人》第6集中 “少女の奔跑”巨人是谁干掉的？": return "三笠·阿克曼";
case "阿卡林的原名是...": return "赤座燈里";
case "幽灵行军不是谁的固有结界": return "梵·斐姆";
case "以下那個不是釘宮四萌?": return "神崎·H·亞里亞";
case "阿良良木历有几个妹妹？": return "两个";
case "在FATE STAY NIGHT 中阿尔托莉雅的职介是什么": return "SABER";
case "哪部是key社所谓的秋？": return"one";
//题库03（未确认） - 266道 - 优子（352275201）提供 - 2014.04.30
case "灼眼的夏娜中女主角的刀名字叫": return "贽殿遮那";
case "《摇曳百合》中京子喜爱的冰淇淋口味是什么": return "朗姆酒葡萄干";
case "命运石之门男主角的网名是": return "凤凰院凶真";
case "以下哪部游戏中没出现东风谷早苗": return "东方神灵庙";
case "《CLANNAD》中的冈崎朋也的配音是谁？": return "中村悠一";
case "《火影忍者》中的第五代火影是谁？": return "千手纲手";
case "桂木桂马的协助者是谁？": return "艾露西";
case "杀手47的后脑勺上有什么": return "条形码";
case "psycho pass里最美警花是谁?": return "宜野座伸元";
case "《数码兽大冒险》中第八位被选召的孩子是？": return "八神光/八神嘉儿";
case "雾雨魔理沙的口癖是？": return "DA☆ZE";
case "切丝papa的生日在几月几日？": return "11月11日";
case "为动画《魔法少女小圆》中佐仓杏子一角配音的声优是？": return "野中蓝";
case "“月有阴晴圆缺”,用科学的观点看待这件事,原因是？": return "地球绕太阳转动,月球绕地球转动,两者转速不一样,出现偏角,使地球掩住了月球的一部分";
case "《我的朋友很少》中,井上麻里奈为哪个角色配音？": return "三日月夜空";
case "游戏《生化危机1》的第一女主角是谁？": return "吉尔·瓦伦蒂安";
case "回转企鹅罐中一共有多少个ED？出了多少个OST": return "10，8";
case "身为纯爷们,绝对从不回头看什么": return "爆炸";
case "以下哪一位不是《最终幻想：零式》的CV": return "钉宫理惠";
case "《大航海时代2》阿兰的特长是什么？": return "会计";
case "钢之炼金术师FA中角色张梅身边总跟着一只什么动物": return "小熊猫";
case "Fate stay night中,士郎击杀Berserker所投影的武器叫？": return "Caliburn石中剑";
case "初音未来的音源提供者是哪个声优？": return "藤田咲";
case "著名电子游戏《上古卷轴》是由哪家公司开发的？": return " Bethesda";
case "石蕗惠汰,羽濑川小鹰,须贺京太郎,大路饼藏四人的共同点[不]包括": return "都是男孩子";
case "在Mugen中,最高的人物等级是？": return "论外";
case "圣斗士星矢的看家技能是？": return "天马流星拳";
case "魔兽世界里的联盟英雄吉安娜是什么职业": return "法师";
case "谁被称为日本动画界的黑泽明？": return "宫崎骏";
case "“世界已完蛋”来自于哪部作品OP的空耳？": return "潜行吧奈亚子";
case "炮姐的最爱是？": return "呱太";
case "美少女战士的作者是哪位漫画家的夫人？": return "富坚义博";
case "陈坤在微博向大家推荐了哪部动画得到群众热烈反应？": return "《Fate/Zero》";
case "正面上我啊是哪个人物的名台词": return "御坂美琴";
case "为《星际牛仔》《攻壳机动队》《Macross F》等动画配乐的著名音乐制作人是": return "菅野洋子";
case "⑨指的是东方project中的那个人物？": return "琪露诺";
case "《天降之物》第一集中从天而降的天使名字是？": return "伊卡洛斯";
case "路过草从最担心的是哪句话？": return "德玛西亚";
case "《海贼王》中与路飞同行的一位厨师是": return "香吉士";
case "自古枪兵的幸运值是多少": return "e";
case "德玛西亚之力此人物出自哪个游戏？": return "《英雄联盟》";
case "虽然我可爱又迷人,但我会招来__。": return "死亡";
case "key社以下哪一部作品不是由京都动画改编？": return "Little Busters!";
case "动漫11区指哪里？": return "日本";
case "《CLANNAD》中,藤林杏的摩托车是什么颜色的？": return "白色";
case "《穷神》中红叶是什么罩杯？": return "AA罩杯";
case "《兽的演奏者艾琳》中的里岚是雄性还是雌性？": return "雌性";
case "东方幻想乡中妖怪之山上守矢神社中的风祝叫什么名字？": return "东风谷早苗";
case "《電腦線圈》中的沙奇(Search Mutton),是甚麼？": return "病毒驱除程式";
case "雾雨魔理沙在东方神灵庙（TH13）中的称号是？": return "普通的魔法使";
case "薛定谔的猫是薛定谔的一个著名实验,其不涉及的问题是 ": return "势垒穿透";
case "《海贼王》中现任海军元帅的是谁？": return "赤犬";
case "暴走漫画的男主角一般都叫什么？": return "王尼玛";
case "小鸟游六花的中二属性是什么？": return "邪王真眼";
case "傅里叶级数是傅里叶在研究哪种物理现象时提出的？": return "热传导";
case "阿姆斯特朗回旋加速喷气式阿姆斯特朗炮“的名字出自哪部动漫": return "《银魂》";
case "火影忍者中4代火影和主角鸣人是什么关系？": return "父子";
case "dota是哪个游戏的地图?": return "魔兽世界";
case "在《死亡笔记》中,是谁杀死了夜神月？": return "硫克";
case "机战里常说的“吉姆王”是出自哪一部作品": return "传说巨神";
case "以下哪一个游戏在早期2D时代的第一部作品不是俯视角？": return "银河战士";
case "无头骑士异闻录中罪歌到11卷出现了几个母体？": return "2个";
case "《魔笛MAGI》中梶裕貴配音的角色是谁？": return "阿里巴巴";
case "兵库北的天气怎么样？": return "雨 19℃ 60%/40% 24岁";
case "“海尔,这是阿包特·泰姆”这句台词出自哪款游戏？": return "星际争霸2";
case "被成为“一生万物、万物归一者”的是": return "Yog-Sothoth";
case "《旋风管家》中的女主角三千院凪的身高是？(直接输入阿拉伯数字） ": return "138";
case "银河英雄传说中男主角杨威利是如何死亡的": return "被地球教刺客刺杀";
case "动漫（雪之少女）泽渡真琴,的口头禅是什么 ": return "啊呜";
case "《魔法少女小圆》的编剧（脚本）是谁？": return "虚渊玄";
case "下列哪个角色不是关智一配音的？": return "基拉·大和";
case "是谁提出“感应电流的磁场总是要阻碍引起感应电流的磁通量的变化“?": return "楞次";
case "动漫《火影忍者》中,宇智波佐助所拥有的瞳术的名字是？": return "写轮眼";
case "《轻音少女》动画中,活动室里养的动物是？": return "乌龟";
case "灼眼的夏娜中夏娜所带的项链中红世之徒的名字是": return "亚拉斯托尔";
case "国产动画片《魁拔》中,魁拔的重生时间是": return "333年";
case "以下哪一款RPG（角色扮演游戏）属于WRPG（欧美角色扮演游戏）？": return "博德之门";
case "C语言中，如果ar是个数组，那么表达式ar[i]与什么等价？": return "*(ar+i)";
case "c语言中换行符是？": return "\\n";
case "某万事屋老板的名字是？": return "坂田银时";
case "以下那部动画的配乐不是梶浦由纪？": return "fate stay night";
case "《某科学超电磁炮》中 御坂美琴的硬币大约能打多少米？": return "50米";
case "以下哪个动漫人物被作为我朝四代隐形战机的爱称？": return "秋山澪";
case "EVA新剧场版中真希波玛丽眼镜镜框的颜色是": return "红色";
case "世界第一公主殿下是谁": return "初音未来";
case "哔哩哔哩是什么类型的网站?": return "弹幕视频";
case "2012年日萌萌王是谁": return "园城寺怜";
case "《穿越火线》由国内哪家公司代理运营？": return "腾讯";
case "下列各项不属于电脑操作系统的是": return "S60";
case "国际标准化组织ISO制定的OSI模型中,路由器工作在哪一层？": return "网络层";
case "下列谁没有担任《机动战士高达V》的机设": return "安彦良和";
case "mugen人物实力一共有几个级别": return "7个";
case "由Nintendo公司发售的8位游戏机的名称缩写是什么？": return "FC";
case "（）,你一定不懂吧。括号里的名字是？": return "心叶";
case "团长的名字是": return "凉宫春日";
case "空之境界中与阴性人格式相反的阳性人格是?": return "织";
case "东方project中不死组指的是那对CP": return "妹红X辉夜";
case "《蔷薇少女》中翠星石的瞳色是？": return "左绿右红";
case "当PCl5 = PCl3 +Cl2的化学平衡常数Kc=1.8M时,在0.5L的容器中加入0.15molPCl5,求平衡后Cl2的浓度": return "0.26M";
case "《to love》中的梨斗的妹妹的配音是谁？": return "花泽香菜";
case "以下哪位角色脸上没有刀疤？": return "阿鲁卡多@HELLSING";
case "“我的这把刀可是涂满了毒药的毒刃”出自于哪部作品": return "勇士闯魔城";
case "下列动画作品中,那一部是由京都动画公司制作的。": return "幸运星";
case "高达鲁姆会战中吉翁一方出动了多少艘姆赛级巡洋舰？": return "69";
case "《加速世界》男主角是谁？": return "有田春雪";
case "《今天开始做魔王》中,涉谷有利第一次是怎么穿越的？": return "被女厕的抽水马桶冲到异界";
case "在缩写“ACG”中字母“G”代表什么？": return "Game";
case "在动漫《叛逆的鲁路修》中,C.C.的头发的颜色是？": return "绿色";
case "凡能从石台上拔出此剑者,即为英格兰的天命之王。出自哪部动漫？": return "命运之夜";
case "3dmax中旋转视图按哪个键": return "alt+鼠标中键";
case "以下哪个不是鬼畜全明星成员？": return "金凯瑞";
case "游戏《帝国时代2》中,中国的特色兵种是？": return "诸葛弩手";
case "“钉宫病”是指有关哪位声优的病症？": return "钉宫理惠";
case "晓美焰的声优是？": return "斋藤千和";
case "下列哪个人物与《kiss×sis》中「住之江理香」的配音相同？": return "蕾蒂西亚（问题儿童都来自异世界？）";
case "请问被称为名作之壁的是什么动漫？": return "Infinite Stratos";
case "我国4个直辖市中哪个面积最大？": return "重庆";
case "《clannad》中藤林杏所养的宠物小野猪的名字是什么？": return "牡丹";
case "葛平的职业是？（说正经的）": return "配音演员";
case "日语的元音的罗马音是？": return "aiueo";
case "农业不发达,必须要有什么？": return "金克拉";
case "《十二国记》的作者是谁": return "小野不由美";
case "《青之驱魔师》是作者是那位？": return "加藤和惠";
case "以下哪一部作品的剧本不是虚渊玄？": return "尘骸魔京";
case "游戏MONSTER HUNTER 3G 中共有几种武器？": return "12";
case "夏目友人帐中的猫咪老师（斑）被动漫爱好者称呼为？": return "娘口三三";
case "元首曾经去过中国的哪个省份？": return "河北省";
case "钉宫四萌哪个出现的最早 ": return "夏娜";
case "动漫《FATE ZERO》中,Rider的名字是？": return "亚历山大·伊斯坎达尔";
case "官方逼死了谁？": return "同人";
case "北极熊的毛是什么颜色？": return "透明";
case "《死神》现任二番队队长大人的名字是？": return "碎蜂";
case "“不要叫我大王,要叫我_______！” 空缺处填？": return "女王大人";
case "拼音“s”的发音是？": return "唇齿清擦音";
case "零之使魔中露易丝在托里斯汀所打工的酒馆前身叫什么": return "鳗鱼之睡床";
case "《龙与虎》中的逢坂大河声优是谁？": return "钉宫理惠";
case "下列各项不属于电脑操作系统的是": return "S60";
case "Operation Skuld出自哪部动画？": return "Chaos;Head";
case "FFF团作为一种自发组织的民间团体主要活动形式是？": return "烧死情侣";
case "以下哪个不是国产游戏。": return "空之轨迹";
case "虚渊玄被称为？（四个中文汉字）": return "爱的战士";
case "一部动漫名称,《XXXX的忧郁》,XXXX应为？": return "凉宫春日";
case "动画《回转企鹅罐》的监督是谁？": return "几原邦彦";
case "《Angel Beast》的女主角是谁？": return "立华奏";
case "以下谁拥有Geass的能力？": return "鲁鲁修";
case "新日暮中的黑暗势力统领是谁？": return "VAN样";
case "XX我成为正义的伙伴了吗？": return "切嗣";
case "400大妈是指": return "东映蜘蛛人";
case "海猫鸣泣之时的武具是叫什么名字？": return "谢斯塔姐妹兵";
case "key君是谁？": return "杉崎键";
case "以下哪个地区代表未出现在金克拉广告中？": return "俄罗斯";
case "以下哪个人不属于ACG界四大人渣？": return "结城梨斗";
case "某部机甲动漫中出现的经典台词是？": return "我爸爸都没打过我！";
case "金坷垃三人组里的非洲人叫什么名字。": return "东仙队长";
case "以下哪部作品没有得过这本轻小说真厉害排行榜的第一？": return "龙与虎";
case "逢坂大河是哪部作品的主角": return "龙与虎";
case "洛天依的声源是": return "山新";
case "《机动战士高达00》中刹那.f.清英的配音是谁？": return "宫野真守";
case "《Love Live!》中的小泉花阳最喜欢的食物是。": return "白米饭";
case "NTSC制式的视频帧率是": return "30fps";
case "博丽灵梦所在的神社是什么？": return "博丽神社";
case "日本剑圣宫本武藏自创的武术是什么？": return "二天一流";
case "“今天的风儿好喧嚣啊”的出处。": return "男子高中生的日常";
case "声优喜多村英梨被中国网友戏称为？": return "酋长";
case "下面哪个角色不是浪川大辅配的？": return "怪盗基德";
case "《虫之歌》中的狮子堂戌子绰号是？": return "小狗";
case "回转企鹅罐中一共有多少个ED？出了多少个OST？": return "10,8";
case "以下不是光色三原色的是？": return "绿色";
case "高达的英文缩写是。": return "GUNDAM";
case "蒙奇·D·路飞出自哪个作品。": return "海贼王";
case "“给我一个支点,我可以撬动地球”这句话是谁说的？": return "阿基米德";
case "《中二病也要谈恋爱》中小鸟游六花的姐姐叫什么名字？": return "小鸟游十花";
case "《英雄联盟》中盖伦是哪个势力的。": return "德玛西亚";
case "《化物语》中战场原黑仪的配音是谁？": return "斋藤千和";
case "春秋战国时期,哪家学说的主张是“兼爱”“非攻”？": return "墨家";
case "《未来日记》中女主叫什么名字？": return "我妻由乃";
case "路飞的爷爷是？": return "海军";
case "“拔刀,拔刀,拔刀”出自哪部漫画？": return "K";
case "下列动画作品中,那一部是由京都动画公司制作的。": return "幸运星";
case "高达鲁姆会战中吉翁一方出动了多少艘姆赛级巡洋舰？": return "69";
case "在缩写“ACG”中字母“G”代表什么？": return "Game";
case "在动漫《叛逆的鲁路修》中,C.C.的头发的颜色是？": return "绿色";
case "凡能从石台上拔出此剑者,即为英格兰的天命之王。出自哪部动漫？": return "命运之夜";
case "日语的元音的罗马音是？": return "aiueo";
case "《十二国记》的作者是谁": return "小野不由美";
case "《青之驱魔师》是作者是那位？": return "加藤和惠";
case "以下哪一部作品的剧本不是虚渊玄？": return "尘骸魔京";
case "游戏MONSTER HUNTER 3G 中共有几种武器？": return "12";
case "拼音“s”的发音是？": return "唇齿清擦音";
case "动画《回转企鹅罐》的监督是谁？": return "几原邦彦";
case "《Angel Beast》的女主角是谁？": return "立华奏";
case "以下谁拥有Geass的能力？": return "鲁鲁修";
case "英雄联盟中国服三大永久免费英雄之一是？": return "流浪法师";
case "声优界中的大辅家族不包括以下哪个姓": return "铃木";
case "《无头骑士异闻录》中,黄巾贼的首领被称呼为？": return "将军";
case "以下哪一个动画原作者是男性？": return "黑塔利亚";
case "空条Q太郎在JOJO里出场了多少部？": return "3部";
case "2ch上某gal讨论板块“叶键版”分别指的是那两个游戏厂商": return "Laef&amp;Key";
case "Fate Zero第二季中的OP作者是谁": return "梶浦由记";
case "以下哪个词是来自日语,意为不引人注意的小知识": return "豆知识";
case "魂中吉原的百华自卫队首领是？": return "月咏";
case "最终幻想零式中,machina最多可以展开强力攻击多少次": return "10";
case "下列哪个不是最早的“讲卫生除四害”之中的“四害”": return "蟑螂";
case "“夏亚你算计我”这句话是哪位人物的名言": return "卡尔玛 扎比";
case "亚洲颜艺三巨头不包括？": return "葛炮";
case "\"只要是活着的东西,即使是神也杀给你看\"是下面哪个人的名言？": return "两仪式";
case "以下哪一位CV不属于声优御三家": return "花泽香菜";
case "中国的第一艘航空母舰叫什么名字": return "辽宁号";
case "以下哪一位不属于type moon？": return "小山广和";
case "光线是波动,也是（ )。": return "粒子";
case "《to love》中的梨斗的妹妹的配音是谁？": return "花泽香菜";
case "“我的这把刀可是涂满了毒药的毒刃”出自于哪部作品": return "勇士闯魔城";
case "高达鲁姆会战中吉翁一方出动了多少艘姆赛级巡洋舰？": return "69";
case "《加速世界》男主角是谁？": return "有田春雪";
case "路飞的爷爷是？": return "海军";
case "“拔刀,拔刀,拔刀”出自哪部漫画？": return "K";
case "《凉宫春日的忧郁》中谁是“外星人”？": return "长门有希";
case "刺客信条中的袖箭不切手指是被谁改进的？": return "艾吉奥";
case "最喜欢从人群中钻出来的关头是谁？": return "吴克";
case "以下哪个游戏不是saga planets的作品": return "さくら、咲きました";
case "战略大作战这部电影当中，主角们做了啥？": return "开着谢尔曼抢银行";
case "开着谢尔曼抢银行": return "花泽香菜";
case "《哆啦A梦》中多啦A梦是从什么时代来的？": return "22世纪";
case "国产动画《魁拔》中，主角的名字是？": return "蛮吉";
case "游戏公司“南梦宫”有一个数字缩写，是什么？": return "765";
case "坦克世界中唯一一辆满仇恨值的黄金色坦克是什么？": return "59式";
case "问更新姬的发式": return "绿色双马尾";
case "网络上11区指的是那个国家？": return "日本";
case "刺客信条中的袖箭不切手指是被谁改进的？": return "康纳";
case "《命运石之门》中凤凰院凶真的配音是？": return "宫野真守";
case "真女神轉生3 狂熱版’中，但丁和人修羅初次見面的地點是？": return "銀座";
case "谁不懂人心了？": return "亚瑟王";
case "黑猫警长每集打四枪出现四个字是?": return "请看下集";
case "在鬼武者3最终关左马介吸收了信长的爱刀所融合出的最强之剑的正确名称是": return "鬼斩左文字";
case "人妻声优門脇舞以的马甲是？": return "杏子御津";
case "与洛天依有关的代码是？": return "66CCFF";
case "《口袋妖怪》历作游戏中，能够让PM的等级提高一级的道具是？": return "等级提升";
case "冻土的旅人中《白色荒野》一章改编自____的小说": return "杰克伦敦";
case "生化危机系列中，僵尸的始作俑者是？": return "T病毒";
case "绑在魂魄妖梦的楼观剑上的花叫什么名字": return "秋樱";
case "《圣斗士星矢》冥王篇中谁是被冥王哈迪斯选中肉体的圣斗士？": return "瞬";
case "以下哪个系列的发行商不是Ubisoft（育碧）": return "孤岛危机系列";
case "《伊克西翁传说DT》玛丽安戴尔的声优是？": return "福山润";
case "《中二病也要谈恋爱》当中丹生谷森夏从“中二病”毕业以后转而相信了什么": return "黑暗圣典";
case "《冰菓》中奉太郎的人生信条是？": return "节能主义";
case "《妖精的尾巴》中，妖精的尾巴公会的第二代灭龙魔导士是": return "拉克萨斯";
case "这个世界上不存在奇迹，有的只是必然与偶然，以及谁做了什么。此话出自什么动漫？": return "悠久之翼（EF系列）";
case "“王师全面占优”出自下列哪个游戏？": return "EVE";
case "幻想乡里操纵境界的妖怪是？": return "八云紫";
case "地球距离月球之间的距离为？": return "384,400千米";
case "nds平台第一款游戏王是哪一年出的": return "2007";
case "miku左臂的数字是多少？": return "01";
case "&lt;犬夜叉&gt;中，戈薇的配音是谁？": return "雪野五月";
case "以下哪位人物是因为视力不好才戴眼镜的": return "黑桐干也";
case "赤座灯里最缺少的是什么？": return "存在感";
case "网游《坦克世界》中，S-51的完全体炮的口径是多少？": return "203";
case "UC系高达作品中象征着量产机的胜利的是哪部作品？": return "机动战士高达第08MS小队";
case "《物语系列》中谁的头发会飞速长长": return "阿良良木月火";
case "天元突破的男主角是谁？": return "西蒙";
case "命运石之门冈部伦太郎经常自称是谁？（名字）": return "凤凰院凶真";
case "以下哪个不是音频处理软件": return "Premiere";
case "《魔法少女小圆》中学姐死的时候失去了身体的哪一部分？": return "头";
case "《未来日记》中，“雪辉日记”的持有者是谁？": return "我妻由乃";
case "以下哪首是洛天依的歌": return "千年食谱颂";
case "动画《刀剑神域》中桐人他女儿结衣在ALO里系统识别种族是？": return "导航妖精";
case "俺はGandom（我就是高达）这句话是谁说的？": return "刹那·F·清英";
//题库04（已确认） - 0道 - Baby（79680406）提供 - 2014.05.09
//题库04（未确认） - 26道 - Baby（79680406）提供 - 2014.05.09
case "动画《魔笛》中小野大辅配音的角色叫什么？": return "辛巴德";
case "琴浦小姐的超能力是？": return "听得见别人的想法!";
case "《天降之物》中藤田咲配音的是谁？": return "樱井 智子";
case " “绅士”一词与下列那个词同义？": return "变态";
case "哪位不是平成三大歌姬?": return "安室奈美惠";
case "桐人是出自哪部动漫？": return "刀剑神域";
case "动画《中二病也要谈恋爱！》中，小鸟游六花的姐姐叫什么名字": return "小鸟游十花";
case "“拔刀、拔刀、拔刀”出自哪部动漫？": return "K";
case "一般来讲“俺妹”指的是哪部动画": return "我的妹妹不可能那么可爱";
case "《好想告诉你》中风早翔太的配音是谁": return "浪川大辅";
case "梶裕贵是《K》中的哪个人物的CV": return "十束多多良";
case "《银魂》的作者是谁？": return "空知英秋";
case "【银魂】中以下哪个人物不是【万事屋】的成员？": return "土方十四郎";
case "滑头鬼之孙二代的名字是？": return "奴良鲤伴";
case "下列哪个不是PSP的按键？": return "☆";
case "《灼眼的夏娜》中的夏娜的配音是谁?": return "钉宫理惠";
case "御坂美琴一般用什么发射电磁炮？": return "硬币";
case "《PSYCHO-PASS》中花泽香菜配音的妹子叫？": return "常守朱";
case "电视剧《巾帼枭雄之义海豪情》中，叫梁非凡去“吔屎啦”的人物是？": return "刘醒";
case "下列哪一项不是犬夜叉中铁碎牙的招式?": return "苍龙破";
case "下面哪个不是小野大辅役？": return "冈崎朋也";
case "《冰菓》中千反田爱瑠的声优是谁？": return "佐藤聪美";
case "执导动画电影《秒速5CM》的日本导演是？": return "新海诚";
case "TARI TARI中冲田纱羽的配音是谁": return "早见沙织";
case "《无头骑士异闻录》里的静雄的配音是谁？": return "小野大辅";
case "《JoJo的奇妙冒险》的作者是谁？": return "荒木飞吕彦";
//题库05（已确认） - 0道 - sxy648896648@qq.com提供 - 2014.05.10
//题库05（未确认） - 4道 - sxy648896648@qq.com提供 - 2014.05.10
case "下列属于酸的是？": return "H2SO4";
case "五岳，是中国五大名山的总称，以下那个选项不属于五岳？": return "峨眉";
case "CaC⒉ 的俗名什么？": return "电石";
case "C7H16有几种同分异构体": return "9";
//题库06（已确认） - 0道 - Feuler loup（410205366）提供 - 2014.05.10
//题库06（未确认） - 20道 - Feuler loup（410205366）提供 - 2014.05.10
case "《地狱少女》中的仙太郎的配音是谁？": return "丰永利行";
case "两仪式有几个人格": return "2";
case "以下哪首歌是Fate/Zero的OP": return "to the beginning";
case "以下那种波不是电磁波？": return "超声波";
case "街机上的《拳皇97》是由哪一个公司制作？": return "SNK";
case "国际通用的标准音的频率是？": return "440Hz";
case "初音岛上的万年萝莉是谁": return "芳乃樱";
case "刀剑神域中，桐人的妹妹名字叫？": return "桐谷直叶";
case "得了什么病也要谈恋爱？": return "中二病";
case "《未来日记》中的女主叫什么名字？": return "我妻由乃";
case "《我的青春恋爱物语果然有问题》女主角的名字是什么？": return "雪之下雪乃";
case "恶作剧之吻男主角名字是（）": return "入江直树";
case "游戏生化危机5的男主角叫什么": return "克里恩雷德菲尔德";
case "柯南的声优是？": return "高山南";
case " S/L大法在游戏中的意思是？": return "利用存档读档的手法";
case "未聞花名的ed【secret base】是翻唱誰的歌？": return "zone";
case "我国4个直辖市中哪个面积最大？": return "重庆";
case "常言道，FFF團不燒什麼？": return "真愛";
case "天上掉下本小册子是什么动漫？": return "死亡笔记";
case "我妻由乃 最常使用的武器是？": return "柴刀";
//题库07（已确认） - 1道 - SongTaste（342566877）提供 - 2014.05.10
case "被称为死神小学生的是": return "柯南";
//题库07（未确认） - 19道 - SongTaste（342566877）提供 - 2014.05.10
case "《圣斗士星矢》是哪一位漫画家的作品?": return "车田正美";
case "以下不是由盛大代理的网游": return "坦克世界";
case "元首到过下列哪个省": return "河北省";
case "《银魂》中真选组副长是": return "土方十四郎";
case "巡音Luka的声源是？": return "浅川悠";
case "一部动漫名称：《XXXX的忧郁》，XXXX应为？": return "凉宫春日";
case "以下那个县和花泽香菜的外号有关？": return "兵库";
case "《真三国无双》由哪家游戏公司开发？": return "KOEI";
case "日本被称为11区源自于什么动画": return "叛逆的鲁鲁修";
case "神奇宝贝里喷火龙的属性是？": return "火系和飞行系";
case "动漫《日在校园》中 伊藤诚被谁干掉的？": return "西园寺世界";
case "洛克人的第一部作品一开始可以选择几关？": return "6";
case "如果有人从草丛里蹦出来,那么他最有可能对你说?": return "德玛西亚";
case "一般来说，传言中的圆桌骑士由几人组成？": return "12人";
case "大陆的《魔兽世界》最早是由哪个游戏运营商代理的？": return "第九城市";
case "以下哪项是游戏《侠盗猎车手:罪恶都市》中不能使用的道具？": return "自行车";
case "\"既不回头，何必不忘”出自哪部游戏？": return "仙剑奇侠传";
case "凉宫春日是（）的团长": return "SOS团";
case "下列声优是90后的是": return "悠木碧";
//题库08（已确认） - 1道 - je（1298674946）提供 - 2014.05.28
case "以下哪款游戏不是Roguelike类型游戏？": return "《Dungeons &amp; Dragons》";
//题库08（未确认） - 597道 - je（1298674946）提供 - 2014.05.28
case "创价学会御本尊(4代目)的sm号是多少": return "sm6999999";
case "以下哪位声优没有参与《化物语》的配音？": return "阿澄佳奈";
case "《数码宝贝》中勇气的徽章是什么颜色的？": return "橙色";
case "《日常》里东云的额头里被放过哪种食物？": return "甜面包";
case "以下哪位角色在《偶像大师》中登场过": return "天海春香";
case "农业不发达，必须要有什么？": return "金克拉";
case "《空之境界》隐藏话独有的一首曲子叫什么？": return "snow falling";
case "《游戏王系列》中第四代主人公的形象化身是哪种动物？": return "龙虾";
case "在收到精神打击时，什么会下降？": return "SAN值";
case "游戏七英雄物语与哪个公司有关": return "姬屋";
case "配音演员葛平因为为哪个角色配音而广为人知？": return "蓝猫";
case "勇士闯魔城的佛祖是个怎样的人": return "热血";
case "TH07是？": return "东方妖妖梦";
case "以下哪位没有被人称作过王？": return "兰斯洛特";
case "《沙耶之歌》中男女主角的初次见面是在：": return "坟场";
case "下列哪部动画是由轻小说改编成的？": return "樱花庄的宠物女孩";
case "《棋魂》中藤原佐为附身到谁的身上？": return "进藤光";
case "《化物语》中的战场原黑仪的配音是谁？": return "斋藤千和";
case "死亡笔记里夜神月的爸爸叫什么名字": return "夜神总一郎";
case "动画《天才麻将少女》中，宫永咲第一次用岭上开花胡牌的符数和番数是？": return "70符2番";
case "光的波动性是谁最先发现的？": return "麦克斯韦";
case "《命运石之门》中，可以发往过去的邮件被称为": return "D-mail";
case "在一部讲述钻头就是男人的浪漫的动画中，他们最常说的是哪一句？": return "你以为我是谁啊";
case "《牧场物语：矿石镇的伙伴们》中向河里丢黄瓜会出现什么？": return "河童";
case "《Fate/extra》中的紅色Saber尼錄的配音員是誰?": return "丹下櫻";
case "堪称日本动漫始祖的是下面哪位动画制作人？": return "手冢治虫";
case "《刀语》中咎儿的口头禅是？": return "切利欧";
case "<psycho-pass>中执法使用的武器是什么": return "支配者";
case "以下哪个角色，不是魔法少女？": return "本间芽衣子";
case "原创动画K中,一般人如何称呼scepter4?": return "青服";
case " 传说中的少女A源自哪部动漫？": return "幸运星";
case "胸不平何以平天下的下一句是？": return "乳不巨何以聚人心";
case "哪位声优上过日本红白歌合战？": return "水树奈奈";
case "西比拉系统的真面目其实是什么？": return "由许多免罪体质者的大脑组成的系统";
case "《虫之歌》中狮子堂戌子绰号是？": return "小狗";
case "魔兽世界里，世界之树诺达希尔底下是": return "永恒之井";
case "新房昭之的别名是": return "南泽十八";
case "《る》是哪位唱见的第二张专辑？": return "ぐるたみん";
case "声优喜多村英梨和同事务所的哪位女声优结成了组合“ARTERY VEIN”": return "今井麻美";
case "DOTA里能减伤害的技能是以下哪个？": return "A.幽灵船";
case "恋爱养成游戏鼻祖“心跳回忆~永远属于你”的女主角叫什么名字？": return "藤崎诗织";
case "魔法少女小圆中和QB签订契约后会变成什么": return "魔法少女";
case "力的单位是什么？": return "牛顿";
case "幻想乡里威严镇四方的那谁（三个汉子）": return "大小姐";
case "血型君里O型的配音是谁？": return "石田彰";
case "以下哪个是勇者王，叛逆的鲁鲁修，枪x剑这三作的共同特点": return "日升制作";
case "《SM判定フォーラム》（SM判定讨论会）曾是以哪个动画的片尾曲？": return "妖狐×僕SS";
case "《零之使魔》中，被称为“神之右手温达鲁乌”的使魔是谁？": return "朱力欧·切萨雷";
case "<<月姬>>中公主的全名是？": return "爱尔奎特 布伦史塔德";
case "《Code Geass 反叛的鲁路修》中日本被不列颠帝国改称为什么？": return "11区";
case "《反叛的鲁鲁修》中，最后一集在“ZERO”的假面之下，杀死主人公鲁鲁修的是谁？": return "朱雀";
case "《化物语》中吸血鬼忍野忍最爱吃的甜点是？": return "甜甜圈";
case "十万个冷笑话里的大娃是怎么“扑街”的？": return "作死";
case "《戏言》中的策师名叫什么？": return "萩原子荻";
case "萨乌森·桑尼号上的冰箱密码是多少？": return "7326";
case "约翰提托最早出现的日期": return "2000年";
case "命运石之门里最初的时间机是运用的哪种电器？": return "微波炉";
case "《超元气三姐妹》中大姐叫什么名字？": return "丸井三叶";
case "乱码1/2里咒泉乡是在": return "中国青海";
case "变态王子与不笑猫中被猫神附身的是？": return "小豆 梓";
case "游戏《暗黑血统2》最后Death将什么交给了Crowfather": return "面具";
case "《AIR》片头曲‘鸟の诗’的作曲者是谁？": return "折戸伸治";
case "《海贼王》中与路飞同行的一位厨师是？": return "香吉士";
case "以下哪个是好的风险测度方式？": return "VaR";
case "东方project里的无节操红白指的是？": return "博丽灵梦";
case "自古幸运E的职业是？": return "枪兵";
case "“非凡哥”的名字是？": return "梁非凡";
case "妖精的旋律女主真正的名字是？": return "露西";
case "灼眼的夏娜中女主角的刀名字叫？": return "贽殿遮那";
case "jojo的奇妙冒险中，第四代jojo是的替身是？": return "疯狂钻石";
case "“菲特今晚留下来”指的是哪一部动画？": return "fate stay night";
case "魔兽世界中，下列技能中哪个需要消耗连击点？": return "伏击";
case "东方project正作中唯一有出场配音的角色是谁？": return "八云蓝";
case "魂斗罗中的水下8关是（）？": return "谣传";
case "请问下列哪个动漫名字正确？": return "会长是女仆大人";
case "在《死亡笔记》中，是谁杀死了夜神月？": return "硫克";
case "以下频道属于上海文广的是？": return "游戏风云";
case "刺客信条2主角的名字是": return "Ezio";
case "以下哪一个不是国产游戏？": return "空之轨迹";
case "灰原哀的真名是什么": return "宫野志保";
case "《スカイクラッドの観測者》与哪部作品有关?": return "Steins;Gate";
case "魔法禁书目录ED2是哪首？": return "See visionS";
case "《我的朋友很少》中的三日月夜空的配音是谁？": return "井上麻里奈";
case "东方红魔乡2面boss昵称是什么？": return "⑨";
case "生前川上伦子没有配过哪部动画的角色？": return "CLANNAD 古河渚";
case "冰菓是2012年几月新番？": return "四月新番";
case "IS中的铃是哪国人？": return "中国人";
case "以下哪位动画角色由女性声优配音？": return "江户川柯南";
case "《我的妹妹不可能这么可爱》中，“黑猫”的真名是？": return "五更琉璃";
case "蝶舞の香蕉君的真名是？": return "Richardo Milos";
case "B站鬼畜御三家之一“葛炮”葛平老师最耳熟能详的作品是？": return "蓝猫淘气三千问";
case "《银魂》中坂田银时佩戴的木刀叫什么？": return "洞爷湖";
case "《Little Busters!》中主角们组建的队伍是？": return "棒球队";
case "《机神飞翔》中ANOTHER BLOOD在MUGEN里的俗称除了“血公主”外还有什么？": return "红朔";
case "以下哪位不是金坷拉三人组里的成员": return "天朝哥";
case "《死神》的主角是？": return "黑崎一护";
case "游戏《DOTA》中，被广大玩家称为“爸爸”的英雄是": return "末日使者";
case "《高达OO》中，德天使是机师是谁？": return "洛克昂·史特拉托斯";
case "游戏《大航海时代4》原始版中的隐藏主角是谁？": return "李华梅";
case "初音未来的英文名是": return "miku";
case "問題兒童都來自哪?": return "異世界";
case "以下哪个动画角色的声优不是山口胜平？": return "《银魂》坂田银时";
case "魔兽世界里的部落英雄萨尔是什么职业": return "萨满";
case "以下哪首歌是《新世纪福音战士》的片头曲？": return "残酷天使的行动纲领";
case "Black Raison Detre是什么意思？": return "漆黑存在的理由";
case "银魂中由银时神乐新八组成的组织名叫？": return "万事屋";
case "试图用眼神震慑对手未果的运动员是": return "越前龙马";
case "在韩国搞笑电影中，大家最熟悉的馆长是？": return "金馆长";
case "在《Fate/Zero》中幸运E指的是哪位英灵？": return "Lancer";
case "以下动画哪一部不是老虚（虚渊玄）的作品？": return "月姬";
case "《凉宫春日的惊愕》中带着微笑发卡的女子真实身份是什么？": return "凉宫春日的另一个自己";
case "草帽海贼团的厨师是谁？": return "香吉士";
case "《魂斗罗》FC一代中第三关boss是？": return "挥舞触手的雕像";
case "亞絲娜在現實世界中的名字是？": return "結城明日奈";
case "架向星空之桥藤堂三姐妹的长女 藤堂 䌷（とうどう つむぎ，Toudou Tsumugi）比一马大几岁": return "三岁";
case "动画《魔法少女奈叶》中的角色高町奈叶的声优是谁？": return "田村由香里";
case "游戏《鬼泣》系列中，但丁的哥哥是谁？": return "维吉尔";
case "错的不是你，是谁呢？": return "远坂时臣";
case "南家三姐妹中的南春香的声优是谁？": return "佐藤利奈";
case "《战神》中奎托斯的身份是？": return "诸神的杀手";
case "克苏鲁神话中当人看到邪神后什么会下降": return "理性值";
case "《秦时明月》中的男主角是谁？": return "天明";
case "\"只要是活着的东西，即使是神也杀给你看\"是下面哪个人的名言？": return "两仪式";
case "日麻中，“绝张字牌等于安牌”的防守理论并不完全正确，因为绝张字牌可能会点下面哪个役": return "国士无双";
case "帕秋莉♂_": return "GO";
case "《白熊咖啡厅》中的LAMA桑是什么动物？": return "大羊驼";
case "在《東京babylon》1992ova中，给昴流配音的声优是？": return "山口胜平";
case "以下那部不是动画制作公司骨头社的作品？": return "机器人笔记";
case "十万个冷笑话的原作者是？": return "寒舞";
case "西尾維新的物语系列不包括？": return "海物语";
case "普朗克常量的物理符号是？": return "h";
case "蝉在叫，人——（两字）": return "坏掉";
case "银魂的英文名是什么？": return "gintama";
case "伊克西翁传说DT中，福山润所配的人物是": return "公主专属的侍♂女";
case "2003娘，或称2K3娘，是哪个公司公司推出的的拟人化萌娘。": return "微软";
case "EVA中真嗣驾驶的是几号机?": return "初号机";
case "老虚的全名叫什么？": return "虚渊玄";
case "银魂中秉着微笑的杀人礼节的人是？": return "夜兔神威";
case "以下哪一个不是<玉响>的圣地？": return "福岛";
case "Mac OS X 10.8的系统代号为？": return "Lion";
case "味精的主要成分是什么？": return "谷氨酸钠";
case "著名声优 田村 ゆかり 因其声线多变，又被大家叫做？": return "田村大魔王";
case "以下哪只主角身边的宠物是不会说话的？": return "名古屋(邻座怪同学)";
case "薛定谔的猫是薛定谔的一个著名实验，其不涉及的问题是": return "势垒穿透";
case "世界上最大的无脊椎动物是什么？": return "乌贼";
case "神舟十号发射时间是什么时候": return "11号17时38分";
case "双子座流星雨出现在每年的": return "12月左右";
case "阿尔萨斯在拿到霜之哀伤并成功转职成死亡骑士之前的职业是？": return "圣骑士";
case "因为天气预报出现在花泽香菜的微笑的时间而出名的日本地名之一是": return "兵库北";
case "以下哪部不是2000年后创作的“高达”系列动画？": return "机动战士高达Z";
case "《科学超电磁炮》中的Railgun是谁的称号？": return "御坂美琴";
case "《战车与少女》中的女主角叫什么名字": return "西住美惠";
case "灵梦什么东西掉得多": return "符纸";
case "“娘口三三”这称呼是出自哪个动画？": return "夏目友人帐";
case "以下哪个游戏机的体积最小？": return "GBM";
case "以下哪首歌不是某科学的超电磁炮的片头曲": return "time after time";
case "声音由中国配音演员山新提供的歌姬是谁？": return "洛天依";
case "在《fate/stay night》中，以下哪个英灵没有参加圣杯战争": return "兰斯洛特";
case "《One Piece》的漫画原作作者是谁？": return "尾田荣一郎";
case "GNU的初始人？": return "Stallman";
case "下面哪个不是现声优御三家？": return "钉宫理惠";
case "哪一项不属于B站科学技术栏目下的小标题？": return "野战技术";
case "请问以下哪位是nico唱见(´･_･`)": return "伊东歌词太郎";
case "《黑子的篮球》中的绿间真太郎的配音是谁": return "小野大辅";
case "《无头骑士异闻录》中折原临也的配音是？": return "神谷浩史";
case "动画《Fate/zero》中，宝具Ex-calibur是什么": return "誓约胜利之剑";
case "没脸月亮的男主CV是谁": return "石田彰";
case "声优冈本信彦所配的以下角色属于人类的是？": return "黒银零";
case "《中二病也要谈恋爱！》中的女主角是谁？": return "小鸟游六花";
case "海贼王中司法岛一役与草帽海贼团交锋的团队是什么？": return "CP9";
case "绫波丽驾驶的是EVA几号机？": return "零号机";
case "下列哪位角色的配音不是钉宫理惠？": return "柊镜";
case "下面哪位不属于钉宫四萌": return "神崎·H·亚里亚";
case "我国第一款图形化MUD网游叫什么？": return "《万王之王》";
case "EVA2号机的驾驶员是？": return "明日香";
case "《甩葱歌》最初改编自哪个国家的歌曲？": return "芬兰";
case "以下哪一款是日本著名游戏公司CAPCOM（卡普空）开发的以日常狩猎为主的游戏": return "怪物猎人";
case "在《刀剑神域》第3集中死掉的妹子叫什么？": return "幸";
case "物语系列中忍野忍所拥有的妖刀名号是？": return "心渡";
case "罪恶王冠的英文缩写是什么": return "GC";
case "假面骑士W里面主角翔太郎没有的记忆体是": return "bomb";
case "下面的作品中哪个不属于东映御三家？": return "圣斗士星矢";
case "人们常说的爱的战士是谁？": return "虚渊玄";
case "《魔法禁书目录》中御坂美琴的“妹妹”之一“番外个体”的超能力等级为": return "LV4";
case "金庸系列武侠著作中，习得“九阳神功”的主角是谁？": return "张无忌";
case "网络用语“奥义很爽”出自哪个人物的台词？": return "易建联";
case "《CLANNAD》中被称为字典帝的人是？": return "藤林杏";
case "卍解出自哪一部动画?": return "死神";
case "在微观领域谁最先提出光子说？": return "爱因斯坦";
case "地球表面的重力加速度约为？（米每二次方秒）": return "9.8";
case "女装山脉是一款怎样的游戏?": return "yooooo";
case "鹿目圆香变身后的武器是": return "开花弓";
case "B站的创始人是谁": return "⑨bishi";
case "以下哪一个动画的原作者不是女性？": return "萌菌物语";
case "以下哲♂学名言哪句是VAN样说的": return "Deep♂Dark♂Fantasy";
case "下列动漫人物中，不是“钉宫四萌”的是哪一个？": return "神崎 H 亚里亚";
case "第一部机动战士高达的监督是谁？": return "富野由悠季";
case "相对论主要是由谁创立的？": return "爱因斯坦";
case "大炮巨舰主义指的是": return "戯画";
case "两仪式的眼睛被叫做什么？": return "直死之魔眼";
case "下列哪一个不是《魔兽世界》中部落阵营的种族？": return "狼人";
case "魔笛magi中的麻麻是谁？": return "贾法尔";
case "动画《Angel Beats!》中，参加卒业式的成员共有几人？": return "5人";
case "以下动画哪一部里面并没有神谷浩史的出场？": return "K";
case "游戏《超级玛丽》原始版（小霸王上的那种）中最后BOSS前的那个小怪是什么？": return "锤子龟";
case "《北斗神拳》中的健次郎在兄弟中排行第几？": return "老四";
case "《命运石之门》中男主角称自己叫什么名字": return "凤凰院凶真";
case "马里奥最初的名字叫什么": return "跳跳人";
case "死神小学生是谁?": return "柯南";
case "香港漫画《老夫子》中，不包含的角色有": return "陈小姐";
case "以下哪个不是《全金属狂潮》中的“耳语者（Whisperd）”？": return "理查德·马度卡斯";
case "超科学电磁炮中的白井黑子是多少级的超能力者": return "4";
case "以下哪个角色是声优江口拓也所役?": return "轻音少女中的店员";
case "兵部京介是怎么称呼明石薰的？": return "children";
case "《悠久之翼》中未来长大后叫什么名字？": return "羽山瑞希";
case "《黑子的篮球》中黑子哲也的配音是谁": return "小野贤章";
case "fate系列中，爱因兹贝尔家族争夺圣杯是为了恢复？": return "第三法";
case "《REWRITE》中神户小鸟的配音是谁": return "斋藤千和";
case "吉姆RGM79的表面装甲是？": return "月神钛合金";
case "以下哪部动画不是京阿尼的作品？": return "我女友与青梅竹马的惨烈修罗场";
case "在漫画Gay界，被统称为“三松组合”的是": return "松崎司，松武，松本いなき";
case "《名侦探柯南》中柯南的名言是什么？": return "真相只有一个！";
case "游戏主机Wii U是哪家公司发售的": return "任天堂";
case "《葫芦娃》是哪个制片厂出品的动画？": return "上海美术电影制片厂";
case "EVA中二号机的驾驶员是谁？": return "明日香";
case "哪一版的口袋妖怪中，皮卡丘是博士直接给小智的": return "黄版";
case "动画《进击的巨人》中，男主角艾伦最先被巨人咬掉的身体部位是？": return "左爪";
case "下面哪位演员没有出演过“少年包青天”中的包青天？": return "严宽";
case "动画《进击的巨人》中兵长利威尔的身高为多少": return "160cm";
case "《罪恶王冠》中“拔剑神曲”的原名是什么？": return "βios";
case "《罪恶王冠》里面从人类体内抽出的心灵具现化物体称为什么？": return "虚空void";
case "JOJO中说出我不想做人了的是谁？": return "迪奥";
case "以下谁不曾出演过多部大河剧": return "堤真一";
case "《全职猎人》的漫画作者是谁？": return "富坚义博";
case "下列不属于STG[射击类]游戏的是": return "东方萃梦想";
case "《Angle Beats!》中音无结弦的妹妹的名字是？": return "音无初音";
case "《幸运星》中泉此方的母亲叫什么？": return "泉彼方";
case "下列哪一个词不是用来形容博丽灵梦的？": return "城管";
case "在《中二病也要谈恋爱》中最能睡觉的妹子是？": return "五月七日茴香";
case "《天降之物》中Nymph是什么类型的万能天使？": return "电子战用万能天使";
case "动画森林好小子中男主角叫什么？": return "卡内奇";
case "以下哪个人被称为爱的战士": return "虚渊玄";
case "主题医院中哪种疾病不需要特殊治疗房间？": return "猫王综合症";
case "德国四号坦克有几个成员": return "5个";
case "《凉宫春日的忧郁》的凉宫春日的声优平野绫还为哪部动漫的主角配音？": return "幸运星";
case "炮姐的真名是什么？": return "御坂美琴";
case "《魔法禁书目录》中，结标淡希的能力名为什么？": return "坐标移动";
case "以下人物谁的声优不是神谷浩史？": return "白熊";
case "\"这不是阿姆斯特朗回旋加速喷气式阿姆斯特朗炮吗?\"的下一句": return "还原度真高啊!";
case "DOTA中魂之挽歌这个技能是以下哪个英雄的？": return "影魔";
case "科学常识，戊烷有几种同分异构体？": return "3";
case "ANGEL BEATS里天使的HAND SONIC莲花状态是LEVEL几": return "4";
case "被称为“炮姐”的是哪位人物": return "御坂美琴";
case "动画“EVA”凌波丽的座驾是哪一个？": return "零号机";
case "《名侦探柯南》的主角柯南的真实身份是？": return "工藤新一";
case "以下哪个人是卫宫切嗣的血亲？": return "伊利亚斯菲尔";
case "《坦克世界》是哪家公司出品的游戏": return "WarGaming";
case "《荒川爆笑团》中的村长是谁？": return "河童";
case "以下哪个人是木叶十二忍之一？": return "奈良鹿丸";
case "在《one piece》顶上战争中被策反的是？": return "斯库亚德";
case "《俺妹》中，桐乃最喜欢的小魔女的名字是": return "梅露露";
case "动画《勇者王》里面的GGG正确拼写为？": return "GaoGaiGar";
case "《银魂》里神乐最爱的零食是？": return "醋海带";
case "TV动画《Fate stay night》中，远坂凛使用的魔术是什么？": return "宝石";
case "以下哪位角色在动漫中被称为学姐？": return "巴麻美";
case "《夏目友人帐》中御影的声优是谁？": return "木内秀信";
case "为蓝猫配音的演员（最广为人知的）是哪位？": return "葛平";
case "洛克人X系列登场的两位主角中，红色的思考型机器人叫什么名字？": return "ZERO";
case "以下哪一款是历史最悠久的弹幕射击游戏？": return "怒首领蜂";
case "流言终结者中格兰特·今原在参加这个栏目以前又参加过什么节目？": return "机器人大擂台";
case "vocaloid歌爱ユキ的老师是？": return "冰山清辉";
case "古剑奇谭是哪个公司研发的": return "上海烛龙";
case "动漫《Angel Beats!》中“SSS”团长是谁？": return "仲村由理";
case "Diels-Alder反应是什么类型的反应？": return "亲电加成反应";
case "《伪物语》中的著名洗脑op是？": return "白金迪斯科";
case "《PHYCHO-PASS》中槙岛圣护的声优的谁？": return "樱井孝宏";
case "以下哪个不是《圣斗士星矢》中冰河的绝招": return "天舞宝轮";
case "《银魂》中的坂田银时的声优是谁？": return "杉田智和";
case "动画《银魂》中的“小屎丸”是": return "猴子";
case "《冰菓》中远垣内将司为什么在社团门外安装红外线收发装置？": return "不让人发现他在屋里抽烟";
case "以下哪个人最早在作品里将上海称为“魔都”？": return "虚渊玄";
case "没有金坷垃~__________": return "怎么种庄稼";
case "《犬夜叉》中的破魔之箭是谁的技能？": return "桔梗";
case "银时的洞爷湖是怎么得到的？": return "电视购物";
case "EVA中男主角操作的是几号机？": return "初号机";
case "伊苏里被双子女神所守护的古代七至宝之一是什么": return "黑珍珠";
case "生物自然选择学说是谁创立的？": return "达尔文";
case "《某科学的超电磁炮》中炮姐放电磁炮需要的道具是？": return "硬币";
case "红色警戒是一款（ ）类型的游戏。": return ":RTS：即时战略游戏";
case "《JOJO奇妙冒险》第二部的男主是？": return "乔瑟夫乔斯达";
case "连我爸爸都没有打过我这句台词是谁说的": return "阿姆罗 雷";
case "电磁炮发射炮弹用到的原理是": return "洛伦茨力";
case "YOOOOOOOOO梦的叫法来源于什么": return "女装山脉";
case "《蜡笔小新》里，野原新之助的妹妹叫什么？": return "野原葵";
case "洛克人X4中使用秘籍获得黑Zero时应按什么方向键+确定键？": return "上";
case "以下属于日本的弹幕网站是？": return "NICONICO";
case "《银魂》中真选组局长近藤勋哪里的毛特别旺盛？": return "屁屁";
case "以下哪一部作品与花店相关？": return "夏雪密会";
case "动画《碧阳学园学生会议事录》中，学生会的会计是？": return "椎名深夏";
case "《妖精的尾巴》中哈比的声优是谁？": return "钉宫理惠";
case "标题“以四脚站立的是野兽，以两脚与意志与虚荣站立的是男人”出自银魂哪一篇章": return "吉原炎上篇";
case "《尸体派对》中森繁朔太郎的配音是谁？": return "柿原徹也";
case "以下哪个版本猎人的假死,在达到命中上限的情况下,依旧有几率出现抵抗.": return "WLK";
case "虚渊玄常被称为什么？": return "爱的战士";
case "电波女与青春男动漫第十二集标题是什么？": return "秒速0.00000000198厘米";
case "罗小黑战记中小黑的配音是谁？": return "山新";
case "下面哪部作品不是骨头社的？": return "黑执事";
case "寒蝉鸣泣之时》发生的村庄名字是什么？": return "雏见泽";
case "钉宫四萌中的以下哪部作品不是出自J.C.STAFF？": return "旋风管家第一季";
case "知名单机游戏“上古卷轴五”主角的特技是什么？": return "龙吼";
case "声优<花泽香菜>没有配音过那部动漫？": return "世界第一初恋";
case "下面哪一部是新海诚的动画？": return "秒速5厘米";
case "战斗种族指的是哪个国家的人？": return "俄罗斯";
case "请问河内著名的____古街在哪个位置？": return "三十六　市中心";
case "bilibili的名字来源是？": return "御坂美琴的外号";
case "以下哪一部不是出自CLAMP笔下": return "绅士同盟";
case "拥有东西南北四宫的男人是谁？": return "真中淳平";
case "《四驱兄弟》中为四驱斗士配音的是谁？": return "森久保祥太郎";
case "从前有个不用剑的剑士，他是~": return "波鲁那雷夫";
case "天鹰战士是哪指部动画？": return "EVA";
case "口袋妖怪游戏中在完全随机的情况下，野外遇到闪光精灵的概率是？": return "1/8192";
case "最终幻想VIII中登场的女主角为：": return "莉诺雅";
case "微软最新家用机的名字是": return "xbox720";
case "<<月姬>>中公主的全名是？": return "爱尔奎特 布伦史塔德";
case "日语“欧尼酱”是什么意思？": return "哥哥";
case "以下哪个声优不是游戏《starry sky》的声优": return "森川智之";
case "《银魂》中万事屋的牌匾上写着什么": return "糖分";
case "《刀剑神域》中的亚丝娜的配音演员是谁": return "户松遥";
case "在动画《军火女王》中，代表我国在非洲利益的是？": return "大星海公司";
case "AIDS的全称是什么?": return "获得性免疫缺陷综合征";
case "宏观经济学中的AS指的是什么？": return "Aggregate Supply";
case "《东方妖妖梦》Phantasm面BOSS叫什么名字？": return "八云紫";
case "欢乐颂是贝多芬第几交响曲中的": return "第九交响曲";
case "以下哪个不是宫野真守配音的": return "龙之峰帝人";
case "minecraft中的creeper（苦力怕）最害怕什么生物？": return "猫";
case "以下哪一位不属于type moon？": return "虚渊玄";
case "《某科学的超电磁炮》里被称作\"炮姐\"的角色全名叫什么?": return "御坂美琴";
case "国产RPG单机游戏古剑奇谭一代的副标题是什么？": return "琴心剑魄今何在";
case "<花牌>和<恋连>告诉我们，名字叫（）的都是苦逼": return "太一";
case "“今天的风儿好喧嚣啊”为了帮朋友解围，这时你会说：": return "隔壁超市薯片半价了，快去买";
case "机战OG2第15话中将哪位四天王最后击破会有特殊奖励？": return "梅基保斯";
case "‘真女神轉生3 狂熱版’中，但丁和人修羅初次見面的地點是？": return "銀座";
case "以下哪位人物没有与QB签订契约成为魔法少女？": return "杨玉环";
case "“孤这一生，无怨无悔，只是，有少许遗憾啊..”是谁的台词？": return "龙溟";
case "篮球员麦迪先生的同事奥登大帝，曾经在媒体面前看过什么漫画书？": return "灌篮高手";
case "《魔兽世界》是哪个游戏公司出品的？": return "动视暴雪";
case "下面哪个不是11区声优“御三家”之一？": return "花泽香菜";
case "以下哪种力不属于性质力？": return "压力";
case "秒速五厘米中男女主角未能交换信件便分离时的BGM是": return "届かない気持ち";
case "_____的科学技术世界第一。": return "德意志";
case " 以下谁一心想做海贼王？": return "路飞";
case "美国圣地亚哥国际农资集团的真实注册地在？": return "河南郑州";
case "中二病也要谈恋爱中，六花一直想要寻找的是": return "不可视境界线";
case "伊卡牧师妹指的是谁？": return "乌贼娘";
case "心理测量者中日本采用什么系统鉴定罪犯？": return "先知系统";
case "《科学超电磁炮》中的电击使（Electro Master）是谁的能力？": return "御坂美琴";
case "日本麻将中，荣和30符4番，得点多少": return "7900";
case "《DOTA2》（刀塔）中地图右上方势力的名字是？": return "夜魇";
case "以下哪款耳机采用了特斯拉技术": return "拜亚T1";
case "《phycho pass》中常守朱的声优是": return "花泽香菜";
case "《科学超电磁炮》中白井黑子所属第几风纪委员支部？": return "风纪委员活动第177支部";
case "《科学超电磁炮》是哪部作品的外传？": return "《魔法禁书目录》";
case "自古（）出CP": return "红蓝";
case "火影忍者里和再不斩一起的叫什么名字？": return "白";
case "天文学上，红移是指": return "天体离我们远去";
case "强袭魔女第一季OP中屏幕下方出现的胖次是什么样式的": return "蓝白条纹";
case "传说中人称兵库北小姐的女性声优是": return "花泽香菜";
case "下列不属于基本粒子的是": return "光子";
case "我大KONAMI社的万年秘籍是？": return "↑↑↓↓←→←→BA";
case "《魔法禁书目录》中茵蒂克丝的配音是谁？": return "井口裕香";
case "以下不是由盛大代理的网游": return "坦克世界";
case "新日暮里中的黑暗势力统领是谁": return "VAN样";
case "《全职猎人》的蚂蚁篇中的“NGL”的代指什么？": return "国家名称缩写";
case "宫野真守给以下哪些人物配过音？": return "夜神月、须王环、纪田正臣";
case "《最终幻想零式》中的哪个角色和《最终幻想7核心危机》中的扎克斯声优相同？": return "Jack";
case "《龙与虎》中逢坂大河的配音是谁？": return "钉宫理惠";
case "金克拉最后给了谁？": return "美国鬼子";
case "被称之为达尔文的斗犬的是历史上哪一位人物？": return "托马斯•赫胥黎";
case "黑化御三家中角色诞生时间最早的是？": return "龙宫礼奈";
case "以下突出环保主题的宫崎骏动画是？": return "《风之谷》";
case "魔笛magi的作者是谁？": return "大高忍";
case "《锁锁美同学@提不起劲》是哪位日本小说家的著作？": return "日日日";
case "在电脑上使用模拟器，在不改变游戏内核的情况下，使用工具辅助操作的游戏方式为？": return "TAS";
case "动画《EVA》中，被称为女神的是谁？": return "凌波丽";
case "《我的妹妹不可能这么可爱》中的黑猫真名叫什么？": return "五更琉璃";
case "《攻壳机动队》中超级黑客不包括谁": return "陀古萨";
case "谁是元首的真爱": return "勃列日涅夫";
case "银魂里面的万事屋的白色的、巨型的狗的名字是什么？": return "定春";
case "下列哪种物质是典型的Lewis酸": return "氨";
case "《中二病也要谈恋爱》第一集中，勇太用那只手先接到六花的小脚的？": return "右手";
case "动画EVA中凌波丽的座驾是？": return "零号机";
case "《空之轨迹》中男主角的名字是？": return "约修亚";
case "我國哪條高鐵線路被譽為世界最長的高鐵線路": return "京廣高鐵";
case "凶真的配音是？": return "宫野真守";
case "游戏Ar Tonelico中，以下哪个诗魔法没有使用Hymmnos？": return "聆紗の子守唄";
case "在B站大家是怎么称呼【泪腺战士】这个up主的？": return "岚少";
case "八云家年纪最大的是谁？": return "八云紫";
case "《进击的巨人》漫画作者是谁？": return "谏山创";
case "《魔法少女奈叶》中旭日之心的最初持有者是？": return "高町薇薇欧";
case "《数码宝贝》八神太一是哪一季的男主角": return "第一季";
case "阿三喜欢玩什么": return "泥巴";
case "《電腦線圈》中的沙奇(Search Mutton)，是甚麼？": return "病毒驅除程式";
case "路飞的生日是日本的什么节？": return "儿童节";
case "Fate/Zero中卫宫切嗣发射起源弹所用的手枪名叫？": return "Thompson Arms Contender";
case "魔法少女小圆中沙耶加所使用的武器是？": return "西洋剑";
case "2012年世萌钻石头环的获得者是谁": return "御坂美琴";
case "《海贼王》中路飞的全名是什么？": return "蒙奇·D·路飞";
case "《CLANNAD》里伊吹风子的CV是谁？": return "野中蓝";
case "LOL的新英雄太强了，我们来削弱____吧。": return "刀妹";
case "mugen中人气角色黑魅灵的原作者是谁？": return "Lates";
case "Minecraft里面的苦力怕英文原名叫什么名字？": return "Creeper";
case "《文学少女》中《沉陷过往的愚者》中“愚者”指的到底是谁": return "芥川一诗";
case "《刀剑神域》中由亚丝娜担任副团长的公会名字是？": return "血盟骑士团";
case "VOCALOID的性别参数的缩略形式是下列哪个？": return "GEN";
case "“团长”一词源于下列哪部动画？": return "《凉宫春日的忧郁》";
case "动画《犬夜叉》中，奈落的哪个分身直到死也一直忠于奈落，毫无怨言？": return "梦幻之白夜";
case "以下哪部galgame不是八月设的作品？": return "G弦上的魔王";
case "《中二病也要恋爱！》中的凸守早苗的声优是谁？": return "上坂堇";
case "老外看《女装正太》的时候会大喊什么？": return "Yooooooooooooooo";
case "下列元素中电负性最大的是？": return "氧";
case "下面那些作品中没有香菜？": return "命运石之门";
case "以下哪个游戏不是EA出品？": return "刺客信条";
case "东方Project是由哪个团体制作的": return "上海爱丽丝幻乐团";
case "《咎狗之血》中Shiki的昵称是什么？": return "四喜";
case "英雄传说：零之轨迹中银的真实姓名是？": return "莉夏·毛";
case "《我的妹妹不可能那么可爱》中高坂京介的手机号是什么": return "091-0455-1212";
case "以下哪款游戏不是暴雪出品?": return "七雄争霸";
case "PSP游戏《弹丸论破》中自称为校长的是谁？": return "黑白熊";
case "《我的朋友很少》中 三日月夜空对柏崎星奈起的外号是？": return "肉";
case "《CLANNAD》的男主人公的是谁？": return "冈崎朋也";
case "以下哪一部动画曾因画面闪动过于频繁，引起观众不适而停播？": return "神奇宝贝";
case "《蜡笔小新》中主人公小新的姓氏是什么？": return "野原";
case "阿卡林是哪个动漫女主的外号": return "赤座灯里";
case "《Durarara!!》中dollars的首领是谁？": return "龙之峰帝人";
case "下列歌曲不属于魔法禁书目录的是": return "Only my railgun";
case "樱花庄的宠物女孩中女主的名字叫什么？": return "真白";
case "兵库北（打一CV名字）": return "花泽香菜";
case "凯瑞甘是哪个种族的女王？": return "虫族";
case "下列哪个是钉宫理惠配音的角色": return "逢坂大河";
case "《战国BASARA》里的伊达政宗的剑术叫什么？": return "六爪流";
case "常盘台中学出自哪部作品？": return "科学超电磁炮";
case "被称为“孝哥”的声优是？": return "梶裕贵";
case "以下哪一部不属于逆后宫向（女性向后宫）动画？": return "我的妹妹不可能那么可爱";
case "所罗门王戒指上的铭文是什么？": return "一切都会过去。";
case "动画《罪恶王冠》中男主角的姐姐名叫？": return "樱满真名";
case "新世纪福音战士中第十七使徒自由天使的外形是？": return "人类形态的少年";
case "魔法少女奈叶中“暴君”奈叶的声优是谁": return "田村由加利";
case "《超时空要塞F》中雪露·诺姆的声优是谁？": return "远藤绫";
case "下列动画中哪一作并非由虚渊玄创作": return "Fate/stay night";
case "EVA中，凌波丽的房间门牌号是多少？": return "402";
case "鉴定枪支的射击残留物是依据什么？": return "硝烟反应";
case "《凉宫春日的忧郁》中长门有希的真实身份是什么？": return "外星人";
case "《中二病也要谈恋爱！》中的男主角是谁？": return "富樫勇太";
case "ACG中的“C”是英文的什么缩写？": return "Comic";
case "恶魔城 月下夜想曲里面，那个区域的怪会掉落真空剑": return "逆城图书馆";
case "动漫《灼眼的夏娜》中夏娜所使用的武器名称为？": return "贽殿遮那";
case "下列哪种语言在语言学文法分类上属于多式综合语？": return "切罗基语";
case "动画“名侦探柯南”中将工藤新一和宫野志保变小的药物叫什么？": return "APTX-4869";
case "用了金坷拉,小麦亩产(数字)": return "1800";
case "eva中紫色的机体是哪一台？": return "初号机";
case "下面那部动画不是P.A.WORKS的作品": return "Little Busters!";
case "《坦克世界》中AP弹是什么类型的弹药": return "穿甲弹";
case "父母分别为AB型血和O型血，则孩子的血型不可能是（）": return "AB和O";
case "哪位人物属于教科书式的傲娇？": return "贝吉塔";
case "当天空出现了鱼鳞云(透光高积云)，下列哪种天气现象会发生？": return "降雨";
case "Gameboy（GB）上的塞尔达传说，时空之章的姐妹篇是？": return "大地之章";
case "在《只有神知道的世界》中，汐宫栞的CV没有为那部作品配音？": return "女高網球部";
case "蛇足最喜欢的中国明星是？": return "林志玲";
case "世界第一的公主殿下是谁？": return "初音ミク";
case "SCP-173的构成材料是？": return "废弃建筑材料";
case "clannad中用什么来实现愿望？": return "光玉";
case "在动漫《某科学的超电磁炮》中，有“超电磁炮”称号的人是？": return "御坂美琴";
case "羟醛缩合反应是在什么环境下由什么离子反应的": return "碱性环境；碳负离子";
case "哪座城市的名字没有出现于游戏《文明5》中？": return "洛连特";
case "哆啦a梦最喜欢的食物是什么？": return "铜锣烧";
case "《魔法禁书目录》中男主角叫什么名字？": return "A上条当麻";
case "漫画《银魂》的作者是谁？": return "空知英秋";
case "红美铃的头上写着什么字": return "龙";
case "轻小说《无头骑士异闻录Durarara!!》是谁的作品？": return "成田良悟";
case "《无头骑士异闻录》中折原临也的声优是谁？": return "神谷浩史";
case "银魂277话到279话野猫篇中桂变成了什么生物？": return "黑猫";
case "境界线上のホライゾン中，角色与其喜好的女性类型对应正确的是": return "点藏·库罗斯优奈特-萝莉";
case "东方系列中青蛙子的全名是": return "泄矢诹访子";
case "质能方程的公式？": return "E=MC²";
case "犬夜叉、L、工藤新一、怪盗基德、kuma（p4g）配音是谁？": return "山口胜平";
case "凉宫春日的忧郁中，哪位是超能力者？": return "古泉一树";
case "下列哪一部动画的监督不是新房昭之": return "刀语";
case "下列哪种立体匹配算法不是全局匹配算法？": return "SSD";
case "动漫《魔法少女奈叶》中，使用“旭日之心”魔导器的是？": return "高町奈叶";
case "下列哪一项不是KEY社的作品？": return "《Routes》";
case "下面哪一个不是《南家三姐妹》中的三姐妹之一呢？！": return "南冬马";
case "银魂里面哪个角色女王属性？": return "阿妙";
case "动画《死亡笔记》中，弥海砂的跟随死神叫什么名字": return "雷姆";
case "二小姐是谁的妹妹？": return "芙兰朵露·斯卡雷特";
case "蜂蜜与四叶草第二季第12话竹本祐太的声优因为什么原因要由野岛健儿代替": return "车祸";
case "国际标准化组织ISO制定的OSI模型中，路由器工作在哪一层？": return "网络层";
case "游戏LOL中，被玩家戏称为“每天要死一百万次”的英雄是谁？": return "提莫";
case "以下哪个解说没有和著名解说满楼水平传过绯闻？": return "阿川";
case "轻小说动画魔法禁书目录中作者镰池和马对超能力的原理说明是？": return "量子力学与混沌原理";
case "<死神>中朽木露琪亚的哥哥叫什么？": return "朽木白哉";
case "《无头骑士异闻录》中纪田正臣的恋人是谁？": return "三岛沙树";
case "下列哪种合成技术是基于对声道的模拟？": return "共振峰模型";
case "以下哪一部作品不是key社发行的galgame?": return "白色相簿2";
case "小说《灼眼的夏娜》作者是？": return "高桥弥七郎";
case "下列哪种不是毒物？": return "小当家的发光料理";
case "螺旋丸出自哪个作品？": return "火影忍者";
case "动画《冰果》是由那个公司制作的？": return "京都动画";
case "葛平在2002年的10月份，在河北的_____、石家庄，河南的安阳为小朋友们做现场的表演。": return "秦皇岛";
case "钢之炼金术师中爱德华把弟弟的灵魂封印在了什么里面？": return "盔甲";
case "《魔法禁书目录》里，“后方之水”的魔法名是什么？": return "Flere210";
case "以下哪个不是Pokémon的译名之一": return "进击的皮神";
case "物语系列中《恋物语》谁是女主角": return "战场原黑仪";
case "《物语》中小忍的胖次是什么?": return "创可贴";
case "《加速世界》中，主人公的名字是？": return "有田春雪";
case "流星花园中有自闭症的少年叫什么名字": return "花泽类";
case "以下哪个是《某科学的超电磁炮》《黑子的篮球》《潜行吧！奈亚子 》的共同点": return "黑子";
case "《初音岛》中白河小鸟的配音演员是谁": return "堀江由衣";
case "下列哪个角色不是新井里美担当的CV？": return "五十岚枫";
case "下面哪一部作品不算在“钉宫四萌”中？": return "绯弹的亚里亚";
case "《摇曳百合》中京子喜爱的冰淇淋口味是什么？": return "朗姆酒葡萄干";
case "人体安全电压是多少伏": return "36伏以下";
case "音乐风格被称为「炸厕所」的p主是？": return "suzumu";
case "盖伦的妹妹是谁？": return "拉克丝";
case "目前宇宙中已知的力被分为4种基本作用力，以下不属于4种基本力分类的是": return "内应力";
case "小野不由美创作、山田章博绘制封面和插图的架空奇幻小说中出现了几个国家？": return "12";
case "森之大统领会用哪个技能": return "肉体演说";
case "以下哪位声优没有参演《无头骑士异闻录》？": return "樱井孝宏";
case "日本麻将中，岭上开花几翻？": return "1";
case "“亿千万的回忆”这首歌出自哪个游戏的BGM？": return "洛克人";
case "《钢之炼金术师》爱德华·艾力克，哪只手和哪只腿是机械铠？": return "左脚 右手";
case "阿银家万事屋里挂的匾额内容是": return "糖分";
case "《咲-saki-》中的安福莉子在队伍中担任的是？": return "大将";
case "《进击的巨人》里三笠是什么种族": return "人类";
case "以下那个音源不属于Vocaloid2?": return "YV1";
case "南家三姐妹中 大姐叫什么名字": return "南春香";
case "下列那个不是数据结构": return "倾斜树";
case "所谓的MNG格式是什么？": return "Multiple image network graphics";
case "____你算计我！": return "夏亚";
case "扩散性百万亚瑟王的出品公司是？": return "SE";
case "谁罪大滔天，搞到百姓怨声载道": return "索尼";
case "光的微粒说是谁提出？": return "牛顿";
case "以下选项中,哪个不是对网游《坦克世界》中S系坦克歼击车704工程顶级炮的称呼？": return "百合⑩";
case "香农采样定理的基本内容是由谁首先提出的？": return "H. Nyquist";
case "动画《战勇。》改编自春原罗宾逊在____上连载的漫画": return "JUMP SQ";
case "以下哪个角色没有在《机动战士高达z》中死亡": return "艾玛";
case "日本被称之为11区源自于哪部动漫？": return "code geass 叛逆的鲁鲁修";
case "《魔法禁书目录》中的御坂美琴的超电磁炮的距离是多少？": return "50米";
case "鬼泣中但丁的大剑叫什么名字": return "叛逆";
case "《BAKUMAN》中真城最高视为劲敌是谁": return "新妻英二";
case "被誉为奥运番的一部东方同人动画叫做？": return "梦想夏乡";
case "蜡笔小新的妈妈叫什么？": return "野原美伢";
case "《伪物语》中的千石抚子的配音是谁?": return "A.花泽香菜";
case "以下哪个不是在TYPE-MOON世界观中被“封印指定”的魔术师？": return "间桐脏砚";
case "现在我们知道，光是一种电磁波，那么同时，它也是一种——": return "超声波";
case "《青之驱魔师》的男主角是谁？": return "奥村燐";
case "《妖精的尾巴》中的哈比的配音是谁？": return "钉宫理慧";
case "五星物语中天照帝与拉克西丝的女儿叫什么名字？": return "卡莲";
case "喜多村英梨在《尸体派对》中为哪位角色配音？": return "持田由香";
case "“真相只有一个！”是谁的名句？": return "江户川柯南";
case "以下哪个不是游戏王的三幻神之一？": return "狮子男巫";
case "“咪啪”是《寒蝉鸣泣之时》里谁的口头禅?": return "古手梨花";
case "毒蛇老外是谁？": return "gigguk";
case "《头文字D》中的秋名山赛道位于哪里？": return "群马县";
case "《半条命》系列主角毕业于哪所理工科院校？": return "麻省理工";
case "“打完这一场仗，就回老家结婚。”一般说过这句话的人最后都会怎样？": return "领便当了";
case "《tolove》中男主结城梨斗被菈菈变成女生之后叫什么名字？": return "夕崎梨子";
case "在游戏《Narcissu（水仙）》中，为濑津美提供泳衣的公司是？": return "白石建筑公司";
case "吉恩军一年战争期间不列颠作战的目标是哪里？": return "加布罗";
case "《我的妹妹哪有那么可爱》中的黑猫的配音是谁?": return "花泽香菜";
case "KONAMI旗下MUG制作团队的名称是？": return "BEMANI";
case "世界线是下列哪部动画中的重要概念？": return "命运石之门";
case "起音的英文名": return "MEIKO";
case "加速世界灾祸之铠篇在小说第几卷完结？": return "第九卷";
case "下列不属于生物酶具有的特点是？": return "单次性";
case "以下的角色中谁不会时间停止？": return "桐谷和人";
case "潘多拉之心主人公的名字是?": return "奥兹";
case "《angel beats》中的天使立华奏最爱吃的食物是什么？": return "麻婆豆腐";
case "“nice boat”是出自那里？": return "SchoolDays";
case "以下角色的配音是钉宫理惠？": return "逢坂大河";
case "被称作大萌神的动漫人物是谁？": return "长门有希";
case "小鸟游六花的姐姐全名是什么？": return "小鸟游十花";
case "动画《空之境界》中，两仪式用的武器是什么？": return "刀";
case "龙之谷中金龙的名字【大陆翻译】？": return "杰兰特";
case "请选出不是由著名声优林原惠所演绎的角色": return "《犬夜叉》神无";
case "以下哪项不是虚渊玄的作品": return "FATE STAY NIGHT";
case "被网友称为“草丛伦”的英雄是？": return "德玛西亚之力";
case "柯南剧场版《通向天国的倒数计时》中，园子把发型做成谁的样子而险些被害？": return "灰原哀";
case "《海贼王》中的的红发海贼团的船长是谁？": return "香克斯";
case "不属于星际争霸的种族是？": return "精灵族";
case "一公斤铁和一公斤棉花哪一个重": return "一样重";
case "银河英雄传说中，杨威利不流血攻占伊谢尔伦要塞是第几次攻略战？": return "第七次";
case "以下哪个不属于哲学三信？": return "救济の心";
case "黑塔利亚》中的意大利的配音是谁？": return "浪川大辅";
case "无头骑士异闻录中出演平和岛静雄的声优是哪位？": return "小野大辅";
case "魔兽世界中如何获得“破碎残阳的”这个称号": return "用1000G购买";
case "哆啦A梦来自于那个世纪": return "22世纪";
case "“我练功发自真心！”是谁的台词？": return "德国BOY";
//题库09（已确认） - 0道 - Ashe（1418974632）提供 - 2014.05.17
//题库09（未确认） - 23道 - Ashe（1418974632）提供 - 2014.05.17
case "《秦时明月》中的男主角是谁？ ": return "天明";
case "《迪迦奥特曼》中谁能变迪迦奥特曼 ": return "大古";
case "“WOW”一词是下列什么游戏的简称 ": return "魔兽世界";
case "四娃的能力和五娃的能力完美的结合在一起就是传说中的……？ ": return "水蒸气";
case "以下哪项不属于诺贝尔奖的范畴？": return "数学";
case "《魔法禁书目录》中穿安全裤的是谁？ ": return "御坂美琴";
case "传说中料理中的极品，杀人旅行之必备良药是？": return "黑暗料理";
case "英雄联盟里德邦总管又叫什么？": return "赵信";
case "有一群人喜欢藏在草丛，然后跳出来袭击路过的敌人，此时他们往往喊的是": return "德玛西亚";
case "以下哪一个能力名不是出自于《魔法禁书目录》&《某科学的超电磁炮》？": return "死线之蓝";
case "生物题：和我签订契约，成为魔法少女吧！是萌兽QB的名言，那他的体表颜色是？": return "白";
case "失忆前的上条当麻怎么称呼御坂美琴？": return "御坂";
case "《犬夜叉》中犬夜叉的哥哥是谁？": return "杀生丸";
case "某科学的超电磁炮中炮姐的硬币弹射程是多少？": return "50米左右";
case "《龙珠》中的龙珠最多有几颗星？": return "七星";
case "以下哪位是站在食物链顶端的人": return "贝爷";
case "进击的巨人中的三笠都被称 ": return "三爷 ";
case "进击的巨人主角": return "艾伦";
case "朝手机号是几位数字": return "11位";
case "bilibili最早出自谁之口？": return "上条当麻";
case "在动画《游戏王GX》中男主角的名字叫什么？": return "游城十代";
case "魔法禁书目录男主人公右手的能力是": return "幻想杀手";
case "下列哪种组合可以构成火箭燃料？": return "混肼+四氧化二氮";
//题库10（已确认） - 0道 - 980182410提供 - 2014.05.18
//题库10（未确认） - 18道 - 980182410提供 - 2014.05.18
case "血蹄酋长指的是哪个声优？": return "喜多村英梨";
case "游戏《缘之空》官方后续作品名字是？": return "悠之空";
case "吴克的发型是什么": return "光头";
case "“大家啊，请成为我的翅膀吧。”这句话是谁说的？": return "坂井悠二";
case "《天元突破》中卡米娜最喜欢说的一句话是什么？": return "你们以为我是谁啊";
case "梦幻西游是哪个公司制作出品的？": return "网易";
case "《少女战车》中的152神教是指？": return "KV-2";
case "不要叫我大王，叫我（）": return "女王大人";
case "“夜阑卧听风吹雨，铁马冰河入梦来”是谁的诗句？": return "陆游";
case "马猴烧酒是什么意思？": return "魔法少女 ";
case "RTS类游戏的中文全称是？": return "即时战略类游戏";
case "《食梦者》中PCP的中文是？": return "完美犯罪党";
case "我的朋友很少，中楠幸村的性别是...": return "女";
case "FFF团出自哪部动漫？": return "笨蛋测验召唤兽";
case "在minecraft中俗称JJ怪的怪物原名叫什么？": return "爬行者（Creeper）";
case "东方Project中，守矢神社的巫女是谁？": return "东风谷早苗";
case "泡面番是什么意思？": return "3~5分钟一集的短番";
case "“你说这个谁懂啊？”出自谁的话": return "基拉·大和";
//题库11（已确认） - 0道 - 仿Chimera君（492335761）提供 - 2014.05.18
//题库11（未确认） - 14道 - 仿Chimera君（492335761）提供 - 2014.05.18
case "以下不是物理气相沉积法（PVD）所用到的技术是？": return "真空蒸发";
case "罪恶王冠中祈妹子的void是什么？": return "闇之长剑";
case "Black★Rock Shooter的原画作者是": return "huke";
case "《北斗神拳》中的南斗凤凰拳传人撒奥萨在MUGEN界被称为？": return "华丽哥";
case "“今天的风儿好喧嚣”出自哪部作品": return "男子高中生的日常";
case "“我要成为新世界的卡密！”是谁的台词和人生目标？": return "夜神月";
case "仰头45°出自哪位动画监督之手": return "新房昭之";
case "“失去恋人的世界会开出怎样的花”这句歌词出自？": return "恋人射杀之日";
case "《fate/zreo》中的金闪闪（吉尔伽美什）的配音是谁": return "关智一";
case "《白熊咖啡厅》里的白熊的CV是谁？": return "樱井孝宏";
case "The New 52是哪间漫画公司的企划？": return "Detective Comics";
case "11区这一称谓源自": return "叛逆的鲁鲁修";
case "《花牌情缘》里竞技歌牌比赛时使用的是《小倉百人一首》中的多少张歌牌": return "100";
case "三国杀中五子良将中被称为装备牌的是哪一位": return "于禁";
//题库12（已确认） - 0道 - 咕噗ブク（931710444）提供 - 2014.06.13
//题库12（未确认） - 9道 - 咕噗ブク（931710444）提供 - 2014.06.13
case "SLB的正确含义是？": return "西瓜回路遮断器";
case "动漫《冰果》中主角们的社团的名字是？": return "古典部";
case "以下哪一个是QQ自由幻想的新手村": return "桃源村";
case "下面哪个不是崛江由衣配音的角色": return "露易丝";
case "“半桶水是打倒不了我的”是谁说的": return "托奇";
case "嘎嘣脆，~~味": return "鸡肉";
case "《某科学的超电磁炮S》中，御坂妹向御坂美琴进行确认的密码是？": return "ZXC741ASD852QWE963";
case "《死神》中十番队副队长是？": return "日番谷冬狮郎";
case "《十二国记》中泰麒的使令是？": return "傲滥";
//题库13（已确认） - 0道 - ˉ時天丶魇楪°（1069671323）提供 - 2014.12.07
//题库13（未确认） - 44道 - ˉ時天丶魇楪°（1069671323）提供 - 2014.12.07
case "物理单位指的是哪位监督": return "山本宽";
case "《地狱少女》中的仙太郎的配音是谁？": return "丰永利行";
case "火影里猿飞阿斯玛的声优叫什么": return "小衫十太郎";
case "IBM5100的CPU型号？": return "P-III";
case " 白色恶魔指的是哪位魔法少女？": return "高町奈叶";
case "EVA里的初号机是什么颜色的？": return "紫色";
case "在动漫《FATE ZERO》中，召开圣杯战争的目的是？": return "召唤圣杯";
case "曾以Fate系列作品获得较大反响的游戏会社TYPE-MOON，以下哪一部是其最早发行的？": return "月姬";
case "Angel Beats!动画由哪个制作公司制作？": return "P.A. Works";
case "自2012年起，世萌提名分为新星组（Nova）和______组（Stella）": return "恒星";
case "《古剑奇谭》的制作公司是？": return "上海烛龙";
case "物语系列的作者是谁？": return "西尾维新";
case "在鬼武者3最终关左马介吸收了信长的爱刀所融合出的最强之剑的正确名称是": return "鬼斩左文字";
case "东方Project的创造者，本名叫做什么？": return "ZUN";
case "世界著名的甲壳虫乐队的Help是哪一年发行的？": return "1965";
case "以下那部galgame没有被制作成动画？": return "G线上的魔王";
case "战斗种族指的是哪个国家的人？": return "俄罗斯";
case "下面哪个是动漫《蔷薇少女》中的人物": return "真红";
case "《天堂II》是哪个国家的游戏公司的产品？": return "韩国";
case "车辚辚,马萧萧_______。后面一句是什么？": return "行人弓箭各在腰";
case "假面骑士W里面主角翔太郎没有的记忆体是": return "bomb";
case "天很冷的时候印度的小朋友一般在哪里玩泥巴？": return "东北";
case "二战中英制17磅反坦克炮的口径": return "76.2毫米";
case "两仪式拥有能力的眼睛叫什么名字": return "直死之魔眼";
case "自然之敌p发售的相关漫画书名是？": return "阳炎 project";
case "《樱花庄的宠物女孩》中的宠物少女是指谁呢？": return "椎名真白";
case "《冰菓》中男二号的原则是什么？": return "说笑限于即兴，不要留下误会";
case "在Android系统中，内核(Kernel)被储存于设备的哪一个分区中？": return "Boot";
case "《轻音少女》中，第二年才加入轻音部的人是谁？": return "中野梓";
case "四年一更的动漫是什么": return "夢想夏鄉";
case "《传送门》系列中,玩家一直所处的实验室属于以下哪个公司?": return "光圈科技";
case "以下不是虚渊玄的作品的是": return "化物语";
case "两仪式有几个人格": return "3";
case "《命运石之门》中，真由理的口头禅是什么？": return "嘟嘟噜";
case " 高达uc EP6的BGM是谁创作？": return "泽野弘之";
case "千反田爱瑠最常说的一句话是什么？": return "私は気になります！";
case "根据VB理论，苯分子中没有下列哪种键？": return "碳碳双键";
case "《进击的巨人》中，分队长韩吉的身高和体重分别是": return "170cm，60KG";
case "在动漫《叛逆的鲁路修》中，C.C.的头发的颜色是？": return "绿色";
case "小鸟游六花的黑伞名称是什么": return "Schwarz Sechs Prototype Mark II";
case "下列哪个兵种不是魔兽3战役中的隐藏单位？": return "奇美拉";
case "东方心绮楼由哪次集会发出试玩版？": return "c83";
case "《在上古卷轴5天际》中主角学会的第一个著名龙吼FUS！RO！DAH！的名字是": return "不卸之力";
case "是哪个卫星发射中心将第2颗北斗导航卫星成功送入预定轨道？": return "西昌卫星发射中心";
//其他（已确认） - 0道 - 2014.06.02
//其他（未确认） - 225道 - 2014.06.02
case "RWBY中的R指的是谁？": return "Red";
case "tv动画《魔法少女小圆》的监督是谁？": return "新房昭之";
case "鬼泣系列但丁从老爸那里继承的武器名字叫什么？": return "叛乱之刃";
case "李靖的三儿子叫什么(三个字)": return "李狗蛋";
case "《那朵花》中面码的原名是什么?": return "本间芽衣子";
case "《欢乐颂》的第一句是怎么唱的？": return "3345 5432 2234 433";
case "《化物语》中的男主角是谁？": return "阿良良木历";
case "小丑巴基经过了重重险境，终于加入了？!!!": return "王下七武海";
case "以下哪个人物不属于海军？": return "空";
case "空耳“阿姨洗铁路”来源于哪部动漫作品的歌曲？": return "创圣的大天使";
case "《灼眼的夏娜》中，坏刃萨布洛克爱恋之人是谁？": return "戏梦乡 梅亚";
case "《潘多拉之心》的作者是谁?": return "望月淳";
case "炮姐的配音是？": return "佐藤利奈";
case "T-34坦克Mod1939配备的主炮口径多大": return "76.2mm";
case "以下哪家动画公司，有\"二大爷\"这个昵称？": return "BONES";
case "Megadeth的作曲风格属于?": return "激流金属";
case "游戏《魔兽世界》中,德鲁伊不能变身为": return "牛";
case "无主之地2是哪个公司的？": return "2K";
case "《银魂》中桂小太郎的萌宠是？": return "伊丽莎白";
case "中二病也要谈恋爱》中小鸟游六花的姐姐叫什么名字?": return "小鸟游十花";
case "Jesse Cook的音乐风格是？": return "Flamenco";
case "《变态王子与不笑猫》的男主角叫什么？": return "横寺阳人";
case "两个人一起吃的是饭，一个人吃的是(...)": return "囧囧囧的饲料";
case "下面哪个人物不是东方鬼畜三人组之一": return "十六夜咲夜";
case "下列哪个动漫角色不是风纪委员？": return "云雀恭弥";
case "杏子御津是哪位声优的马甲": return "门胁舞以";
case "Fate stay night中，士郎击杀Berserker所投影的武器叫？": return "Caliburn";
case "物理四大基本力是哪些？": return "万有引力 弱相互作用力 强相互作用力 电磁力";
case "战地2里美军狙击手的初始主武器是什么": return "M99";
case "一个农田的全部生物属于？": return "生态系统";
case "八田美咲的准确身高是？（以伏见透露的为准）": return "166.9";
case "被称为\"LOL\"的游戏是什么？": return "英雄联盟";
case "庫洛魔法使中的庫洛牌一共有多少張？": return "53";
case "东方project被关地下室的是谁？": return "芙兰朵露";
case "下列哪个设定存在于魔兽世界中？": return "种族语言";
case "《XXXHolic》中是那种动物给侑子他们送去了关东煮？": return "狐狸";
case "爱の战士本名为？": return "虚渊玄";
case "TV动画《Air》 神尾观铃喜欢喝的 蜜桃果汁 浓缩度是多少？": return "500%";
case "《化物语》中忍野忍的眼睛是什么颜色？": return "金色";
case "东方project乐曲碎月的曲名来源于谁单手碎月的典故?": return "伊吹萃香";
case "\"我代表月亮消灭你\"这句经典台词出自于哪部动画？": return "《美少女战士》";
case "连我__都没打过我！": return "爸爸";
case "犬夜叉中属于杀生丸自己的武器叫什么": return "爆碎牙";
case "《化物语》中战场原黑仪被什么怪异缠上了？": return "螃蟹";
case "\"我这把刀可是涂满了毒的毒刀\"出自?": return "勇士闯魔城";
case "动漫简介：花季男惨遭毒手变侏儒，痴情女真心不变仍同居": return "名侦探柯南";
case "以下哪个不是对长期在家的人的称呼？": return "ACGER";
case "世界上的第一台电子计算机叫什么?": return "Eniac";
case "游戏《elona》中每过多长时间出现以太之风？": return "3个月";
case "fate系列中谁不是saber的主人": return "远坂凛";
case "以下哪一位动漫人物和其他三位不是同一作品的人物？": return "漩涡鸣人";
case "以下哪句台词是jojo中迪奥布兰多的": return "我不做人了！";
case "下列哪部作品不是出自“爱的战士”虚渊玄之手？": return "空之境界";
case "《少年同盟》中双胞胎哥哥的名字是？": return "浅羽悠太";
case "以下那位角色的配音不是钉宫理惠？": return "木下秀吉";
case "声优山寺宏一与哪位女声优于2012年6月17日注册结婚？": return "田中理惠";
case "犬夜叉》中阿篱是谁的转世？": return "桔梗";
case "游戏《上古卷轴》中“我以前和你一样是个冒险者，直到我的______中了一箭": return "膝盖";
case "《笨蛋测验召唤兽》中木下秀吉的性别是？": return "秀吉";
case "自挂东南枝前面一句是？": return "徘徊庭树下";
case "我们一般用\"⑨\"来称呼谁？": return "琪露诺";
case "《THE UNLIMITED兵部京介》是那部作品的外传？": return "绝对可怜小孩";
case "突然间，人群中钻出来一个（ ）": return "光头";
case "元首的愤怒：That's why.........！": return "俺悲愤";
case "下面哪家厂商不是手办御三家之一": return "KOTOBUKIYA";
case "<幸运星>中提到的“迷の少女A”指的是?": return "泉此方";
case "上古卷轴通常被叫做什么": return "老滚";
case "黑岩射手【Black★Rock Shooter】原人设的作者是？": return "HUKE";
case "化物语的战场原黑仪被什么怪异附体": return "重蟹";
case "小鸟游家要小心一个叫什么名字的男人": return "X太";
case "请问伊藤诚的父亲叫什么": return "泽越止";
case "《幸运星》中常和此方一起玩网游的是": return "老师";
case "传说中从天而降砸到牛顿的是": return "苹果";
case "XXX年的波纹": return "495";
case "被誉为\"物理学圣剑\"的武器全称是什么？": return "撬棍";
case "命运石之门》中关智一是哪个人物的配音": return "桥田至";
case "老子不做人了，JOJO!」以上台词出自哪部动画": return "《JOJO的奇妙冒险》";
case "《CLANNAD》中，冈崎朋也的CV与《冰果》中的_______是同一人。": return "折木奉太郎";
case "以下哪位角色的发色和其他三位有着明显差异？": return "芙蓉枫";
case "《仙剑奇侠传四》中男主角的名字？": return "A.云天河";
case "麦当劳叔叔的鞋子有几公分长": return "大概4个汉堡那么长";
case "注明台词“我很好奇！（私、気になります！）": return "冰菓";
case "DEATH NOTE的漫画家是谁？": return "小畑健&amp;大场鸫";
case "以下哪位动漫角色是\"三无\"属性": return "绫波丽";
case "MUGEN是以下哪个单词？": return "无限";
case "以下哪句是LOL中盖伦的台词？": return "人在塔在！";
case "《化物语》中的神原骏河的配音是谁?": return "泽城美雪";
case "今天又找到好蘑菇______~": return "DA☆ZE";
case "以下不是吃货的角色是哪一个？": return "四条贵音";
case "《中二病也要谈恋爱》中女主角的全名是？": return "小鸟游六花";
case "【钉宫四萌】不包括以下的哪位？": return "阿尔方斯";
case "动画《龙x虎》中曾和大河一起唱过歌的人是谁？": return "栉枝实乃梨";
case "WTF是什么意思": return "WHAT THE FUCK";
case "《英雄联盟》中盖伦与拉克丝是什么关系？": return "兄妹";
case "\"你已经死了\"是哪部作品中的名台词？": return "北斗神拳";
case "广东音乐中的粤胡又称为": return "高胡";
case "银魂中吉原的百华自卫队首领是？": return "月咏";
case "fate zero 中职阶为Assassin是谁？": return "哈桑·萨巴赫";
case "魔神转生的游戏制作公司是？": return "阿托拉斯";
case "白色相簿2中冬马和纱的工作是什么": return "钢琴家";
case "西住美惠在最后的战斗中坦克掉了几个轮子": return "2个";
case "以下哪一項是正確的動畫名稱？": return "鎖鎖美同學@提不起勁";
case "王♂之降临，王指的是？": return "Billy Herrington";
case "银魂中_______的生日是儿童节": return "神威";
case "金坷垃三人组中，没有哪国人民": return "法国";
case "《Minecraft》中，会静悄悄的接近玩家然后猛烈爆炸的绿色怪物是？": return "JJ怪";
case "（），你一定不懂吧。括号里的名字是？": return "心叶";
case "请问，在《胧村正妖刀传》中，百姬打败鬼助后得到的刀是": return "胧村正";
case "请问《圣斗士星矢》中的青铜圣斗士男子偶像团体组合又被称为：？": return "五小强";
case "洛克人ZERO中率领斩影军团的四天王是谁": return "漆黑的幻影~潘恩托姆";
case "比利海灵顿最喜欢的运动是什么？": return "摔跤";
case "以下哪个属性不是如月伸太郎的？": return "矮子";
case "弹幕中经常出现的\"战斗力只有5的渣渣": return "龙珠";
case "动漫《K》中，镰本力夫有什么特异体质？": return "冬胖夏瘦";
case "“连我爸爸都没有打过我！”\"我\"指的是谁？": return "罗·雷";
case "《足球小将》中天才三杉淳有什么病？": return "心脏病";
case "高达AGE中福利特的千古名句是？": return "生命可不是玩具！";
case "曾在大陆电视上播出的，取材于古印度神话，描述了“创造神梵天”和“破坏神湿婆”之间的战斗，主角为\"八部众的日本动画是以下哪一部？": return "天空战记";
case "下列avg作品中哪一款的攻略对象是可爱的男孩子？": return "《女装山脉》";
case "下面哪个不是《龙与虎》中的人物？": return "八坂真寻";
case "半导体二极管(硅管)的导通电压是多少": return "0.6-0.8V";
case "为《高达SEED》、《舞-HiME》、《空之境界》等动画谱写配乐的日本ACG界知名音乐制作人是": return "梶浦由记";
case "《神次元游戏海王星V》中，拉丝缇修（Lastation）的守护女神是哪个？": return "诺瓦露（Noire）";
case "niconico著名舞蹈组合【DANCEROID】最早由几名成员组成？": return "3";
case "迈阿密热火获得第一个总冠军的赛季，队中的主力大前锋是谁": return "哈斯勒姆";
case "以下哪一只是醉酒萝莉？": return "伊吹萃香";
case "在《凉宫春日的忧郁》09版动画中，“永无止境的八月”共重复了多少次": return "15532";
case "大家喜欢叫御坂美琴什么？": return "炮姐";
case "游戏〈我的世界〉中哪种生物不能繁殖？": return "猫";
case "日剧《我们都是超能力者》中主角的超能力是？": return "读心术";
case "《黑子的篮球》中的幻之第六人是谁？": return "黑子哲也";
case "《绝园的暴风雨》中的杀死不破爱花的犯人是谁？": return "不破爱花";
case "【魔法禁书目录】里面的上条当麻是什么能力者？": return "无能力者";
case "咎狗之血的主角叫什么": return "AKIRA";
case "钻头是男人的什么？": return "浪漫";
case "日剧《伽利略》（或译作《神探伽利略》）的男主演名字是？": return "福山雅治";
case "《名侦探柯南》中工藤新一是被灌下代号为什么的毒药致使身体缩小的？": return "APTX-4869";
case "下列哪个不是全明星之一": return "小仓优子";
case "络缲茶茶丸的启动时间是什么时候？": return "2001年6月5日";
case "海贼王里路飞的爷爷叫什么?": return "蒙奇·D·卡普";
case "少女幻葬~Necro Fantasy是哪一位的主题曲": return "八云蓝";
case "《三国杀》中，郭嘉属于的势力是？": return "魏";
case "在计算机内部，一切信息的存取、处理和传送的形式是": return "二进制";
case "当麻的后宫数量是？": return "破万";
case "在bilibili上up主头像边有闪电标识的代表什么意思": return "bilibili认证";
case "哪个不是K-on！中的人物？": return "巴麻美";
case "幽幽子大人的食物，魔法森林烧烤店的店主是的外号是？": return "小碎骨";
case "以下哪个不是V家人物?": return "黑岩";
case "以下哪个地名是丧心病狂的香菜黑们对花泽香菜的代称？": return "兵库北";
case "下列哪个字母组合是国际最萌大会（世萌）的英文缩写？": return "ISML";
case "硝基盐酸为什么能溶解金？": return "氧化";
case "东方project游戏初始界面游戏图标是谁？": return "博丽灵梦";
case "一般来说，传言中的圆桌骑士由几人组成？": return "12人";
case "《名侦探柯南》中服部平次是哪里人？": return "大阪";
case "宇多田光的<EXODUS>中与爱伦?坡的《乌鸦》有关的歌曲是哪一首？": return "KREMLIN DUSK";
case "下面谁给《机动战士高达seed 》中的拉克丝?克莱茵配过音": return "田中理惠";
case "原创动画《k》当中哪两个人的身体调换了": return "伊佐那社 阿道夫?K?威兹曼";
case "养女党和养鸡党的梗来着哪一部动漫": return "真实之泪";
case "死神的作者是？": return "久保带人";
case "以下哪个是《凉宫春日物语》中的超能力者？": return "古泉一树";
case "网游《坦克世界》中，哪辆金币车在国服中保有量最多": return "59式";
case "国产动画片《大闹天宫》中，没有出场的人物是": return "唐三藏";
case "下列人物不属于幻想乡三大总受的是": return "帕秋莉";
case "《某科学的超电磁炮》中LV5第五位“心理掌控”叫什么名字": return "食蜂操祈";
case "动画片《成龙历险记》是哪国出品？": return "中国";
case "《戏言》的作者是谁": return "西尾维新";
case "《最终兵器彼女》中的女主角是谁？": return "千濑";
case "被尊称为\"伪娘始祖\"的人物是？": return "宫小路瑞穗";
case "PSYCHO-PASS的中文译名是？": return "心理测量者";
case "《梦幻西游》中拜师不能超过多少级？": return "25级";
case "红魔馆坐落的地点是": return "湖畔";
case "自古什么出CP？": return "红蓝";
case "JOJO家族有什么形状的胎记": return "星形";
case "“只要杀了他，雪忆随便你搞”出自？": return "雾之本境";
case "动漫界“好男人”指的是谁？": return "阿部高和";
case "《秒速5厘米》的导演是谁": return "新海诚";
case "《Code Geass 反叛的鲁路修》中鲁路修?兰佩路基（成年）的日本声优是谁？": return "福山润";
case "宠物小精灵中暴鲤龙的属性是？": return "水+飞";
case "MMD的全称是?": return "MikuMikuDance";
case "《银魂》中神乐的配音是谁？": return "钉宫理惠";
case "名句“蛋糕是个谎言”出自哪款游戏？": return "《传送门》";
case "《最终幻想13》中，雷霆的召唤兽是？": return "奥丁";
case "绰号“酋长”的声优是": return "喜多村英梨";
case "京都动画幸运星经常neta另一个和该动画女主角同声优的作品，这个作品是？": return "凉宫春日的忧郁";
case "《化物语》的原作小说作者是谁？": return "西尾维新";
case "下列哪个不是伊藤静的马甲": return "桂雏菊";
case "因广开后宫而被称作“诚哥”的动漫人物出自以下哪部动漫？": return "《School Days》";
case "博丽灵梦常常露出什么？": return "腋下";
case "京都动画是几几年成立的": return "1981年";
case "使命召唤第四代的标题是？": return "现代战争";
case "炮姐在自动售货机买饮料需要花多少日元？": return "免费";
case "东风谷早苗的发饰是？": return "丝带";
case "下面那个角色不是由花泽香菜配音的？": return "小唧";
case "虚渊玄未参与以下哪部作品？": return "Fate/stay night";
case "《仙剑奇侠传5》的男主角叫什么？": return "姜云凡";
case "王水是以下那两种物质的混合溶液": return "硫酸和硝酸";
case "《那朵花》的原名为什么": return "我们仍未知道那天所见那朵花的名字";
case "《Fate/stay night》中阿尔托莉雅的职阶是什么？": return "Saber";
case "日本剑豪佐佐木小次郎的宝刀叫什么？": return "备前长船长光";
case "进击的巨人中的三笠都被称": return "三爷";
case "S/L大法在游戏中的意思是？": return "利用存档读档的手法";
case "在动漫《FATE ZERO》中，召开圣杯战争的目的是？": return "召唤圣杯";
case "我以前和你一样也是个冒险家，直到": return "我膝盖中了一箭";
case "被称为野生诹少的是？": return "蛇足";
case "以下哪位鬼畜素材人物属于“兄贵”系列？": return "VAN样";
case "《钢之炼金术师》中爱德华失去了身体的哪部分": return "左腿和右臂";
case "游戏《女装山脉》中，主人公的名字叫什么": return "度会行人";
case "下列哪一个是《进击的巨人》中人类城墙的名称": return "Sina";
case "白色相簿的游戏最早是的发售日期是？": return "2010年6月24日";
case "声优女王是谁？": return "林原惠";
case "我曾经是个冒险者，直到我的膝盖中了一箭”这句话出自哪款游戏？": return "上古卷轴5";
case "东方设定里的古明地恋和古明地觉的关系是什么？": return "姐妹";
case "被称为人渣诚的是哪位？": return "伊藤诚";
case "《黒之契约者》中黑的中文名叫什么？": return "李舜生";
case "《超电磁炮》中炮姐的能力排行第几？": return "第三";
case "被誉为动漫界\"国歌\"的是下列哪首歌？": return "鸟之诗";
case "THD是什么意思？": return "东方DOTA";
case "死后世界战线的领导者是谁？": return "仲村由理";
case "clamp现在有几个人": return "4";
case "以下那部不是宫崎骏的作品？": return "夏日大作战";
case "在游戏《口袋妖怪》系列中，能对岩殿居蟹造成2倍伤害的攻击为下列哪个系？": return "钢系";
case "组长的真名是什么？": return "杉田智和";
case "《未来日记》的女主角的名字叫": return "我妻由乃";
case "动画《空之境界》男主角的名字是？": return "黑桐干也";
case "风音是哪位声优的马甲": return "樱井浩美";
default: return undefined;
  };
};
